[wip] totp: set and verify tools
decred/politeiagui pull request #2127
Opened 2020-09-04 16:07 UTC by victorgcramos

This PR Closes #2120 

### Solution description

This is a WIP. Description will be updated after work is complete.

### Preview

<img width="1288" alt="Screen Shot 2020-09-04 at 1 06 02 PM" src="https://user-images.githubusercontent.com/22639213/92261204-6fc39e80-eeaf-11ea-94c2-4fb65c4142e9.png">

2020-12-02 16:22 UTC, alexlyp approved these changes
tACK works well and looks pretty good.

2020-12-07 21:24 UTC, victorgcramos commented
Now, since TOTP is required on login for enabled users, I made a couple of changes on the instructions, added some confirmation modals, and improved the TOTP setup flow.

Here's a quick preview:
<img width="1336" alt="Screen Shot 2020-12-07 at 6 10 49 PM" src="https://user-images.githubusercontent.com/22639213/101405900-8bc44b00-38b7-11eb-9051-c29e909e0e7b.png">

<img width="1338" alt="Screen Shot 2020-12-07 at 6 18 30 PM" src="https://user-images.githubusercontent.com/22639213/101406732-9e8b4f80-38b8-11eb-81fb-aa137c95383b.png">

<img width="1338" alt="Screen Shot 2020-12-07 at 6 19 09 PM" src="https://user-images.githubusercontent.com/22639213/101406801-b4991000-38b8-11eb-8ace-b537f9fe9fb5.png">
<img width="1339" alt="Screen Shot 2020-12-07 at 6 23 06 PM" src="https://user-images.githubusercontent.com/22639213/101407175-4739af00-38b9-11eb-8fed-41d3b6aae991.png">
<img width="1336" alt="Screen Shot 2020-12-07 at 6 19 41 PM" src="https://user-images.githubusercontent.com/22639213/101406862-cd092a80-38b8-11eb-9268-f3a3bd6fd509.png">

<img width="1338" alt="Screen Shot 2020-12-07 at 6 20 26 PM" src="https://user-images.githubusercontent.com/22639213/101407078-1f4a4b80-38b9-11eb-9107-5b7bc42b2c26.png">
<img width="1338" alt="Screen Shot 2020-12-07 at 6 20 34 PM" src="https://user-images.githubusercontent.com/22639213/101407084-21140f00-38b9-11eb-8400-2aad09c6e067.png">

2020-12-10 21:10 UTC, alexlyp commented
works great on login!

only suggestion i have is to have a definite cursor or highlight on mousing over an already populated digit.  

Currently once a digit is populated the blue line doesn't change to it's hard to know if you have that digit selected.

Maybe change it to a slightly darker blue tone when already populated and hovered?

2020-12-16 20:10 UTC, tiagoalvesdulce reviewed
Good job, left a few comments.

2020-12-16 20:10 UTC, tiagoalvesdulce commented on src/containers/User/Totp/Set.jsx
> +        {totp && (
this is boolean expression is a bit unclear since because if `SetTotp` receives `undefined`, it will default to `{}` and be `true` which is not very clear for the reader. You should be more explicit here saying: `totp !== null` or removing the default `{}` and moving the `totp &&` expression up.

2020-12-16 20:10 UTC, tiagoalvesdulce commented on src/containers/User/Totp/Totp.jsx
> +  const handleOpenTOTPModal = (isReset = true) => (code, cb) => {
This param could be renamed to `shouldShowResetInstructions` or `isTotpSet`.

2020-12-16 20:10 UTC, tiagoalvesdulce commented on src/containers/User/Totp/Verify.jsx
> +  onVerify: PropTypes.func,
I think this component doesn't make sense unless the onVerify function is required

2020-12-16 20:10 UTC, tiagoalvesdulce commented on src/components/DigitsInput/DigitsInput.jsx
> +  onFill: PropTypes.func
`onFill` is never used and `className` and `code` are used but not defined in the propTypes.

2020-12-16 20:44 UTC, thi4go reviewed
Hey mate functionality working great, nice job. Got just few comment.

As of now, I have to fail a login first to enable totp code insertion, and then do a successful login. Not sure the best way to go here, but I thought of two things; we can store this info on the user's browser (not a fan of this), or we could add a checkbox on the login form that shows/hides the totp input part.

2020-12-16 20:44 UTC, thi4go commented on src/containers/User/hooks/useTotp.js
> +export default function useTotp() {
sweet hook

2020-12-16 20:44 UTC, thi4go commented on src/components/DigitsInput/DigitsInput.jsx
> +const getCodeArray = (code = "", length) => {
would be great to have a comment that explains what this function accomplishes for the component as a whole

2020-12-18 14:08 UTC, victorgcramos commented on src/containers/User/Totp/Set.jsx
> +        {totp && (
I guess we don't need this `totp` checker anymore. The parent component already forces the loading state when totp is undefined. I think removing it is okay.

2020-12-18 14:17 UTC, victorgcramos commented on src/containers/User/Totp/Verify.jsx
> +  onVerify: PropTypes.func,
I agree!

2020-12-18 14:43 UTC, victorgcramos commented on src/containers/User/hooks/useTotp.js
> +export default function useTotp() {
thanks bro!

2021-01-20 15:56 UTC, tiagoalvesdulce requested changes
Code is looking pretty good.

Some points:

1. These should be submitted when hitting enter.

<img width="514" alt="Screen Shot 2021-01-20 at 12 45 29" src="https://user-images.githubusercontent.com/13955303/105200214-5a79a480-5b1e-11eb-8c19-d20dd88f588e.png">

<img width="510" alt="Screen Shot 2021-01-20 at 12 46 44" src="https://user-images.githubusercontent.com/13955303/105200219-5cdbfe80-5b1e-11eb-9dd6-173da38fae34.png">

2. The switch should be focused after hitting tab on password (`tabindex`)

<img width="572" alt="Screen Shot 2021-01-20 at 12 48 16" src="https://user-images.githubusercontent.com/13955303/105200356-85fc8f00-5b1e-11eb-8137-740bf89bdfe6.png">

3. This loading indicator should be centered

![2facauth](https://user-images.githubusercontent.com/13955303/105200601-c65c0d00-5b1e-11eb-97c1-0873379f2356.gif)

4. Question: Can you edit the recommended logo in the TOTP authenticator app?

![image](https://user-images.githubusercontent.com/13955303/105201533-c4df1480-5b1f-11eb-88f0-c89d87751f6a.png)

2021-01-20 23:06 UTC, victorgcramos commented
@tiagoalvesdulce updated the code to include the requested changes. About item 4, I don't think we can change that. From what I could see, this is up to the TOTP App, not the code itself.

After taking a look at https://github.com/pquerna/otp (the one we use on backend), I couldn't figure a way out to handle this default image.

2021-01-25 14:15 UTC, tiagoalvesdulce approved these changes
Looking great!

2021-01-25 14:15 UTC, merged