Move logout permanently to account tab
decred/politeiagui pull request #2226
Opened 2020-11-30 18:13 UTC by tiagoalvesdulce

Closes #2225 

### UI Changes Screenshot

<img width="1171" alt="Screen Shot 2020-11-30 at 15 12 29" src="https://user-images.githubusercontent.com/13955303/100647557-78950680-331e-11eb-9e6e-379a27937aba.png">

2020-11-30 18:35 UTC, thi4go requested changes
Hey mate, thanks for this PR, this is indeed much better UX for clearing user data.

I suggest we add a confirmation modal or smth similar for the `Clear data` button, so that we can avoid headaches with missclicks. Currently it wipes the data with the first click, which could lead to unintended behaviour for users that are not careful with this.

2020-11-30 19:01 UTC, tiagoalvesdulce commented
Good idea, will do

2020-12-01 16:18 UTC, thi4go approved these changes
Sweet. LGTM!

2020-12-03 21:17 UTC, amassarwi approved these changes

2020-12-03 21:17 UTC, merged