e2e: Admin account tests
decred/politeiagui pull request #2297
Opened 2021-01-21 13:11 UTC by thi4go

This PR adds the remaining tests for `adminAccount.js` test file, described in https://github.com/decred/politeiagui/issues/2229

2021-01-25 14:47 UTC, tiagoalvesdulce requested changes
I noticed that are some actions still not covered. eg:

```
MANAGE_USER_EXPIRE_NEW_USER_VERIFICATION
MANAGE_USER_EXPIRE_RESET_PASSWORD_VERIFICATION
MANAGE_USER_EXPIRE_UPDATE_KEY_VERIFICATION
```
 
 Do you want to cover them in separate PRs?

2021-01-25 14:47 UTC, tiagoalvesdulce commented on src/containers/User/Detail/Account/AdminAccount.jsx
> +          {isdeactivated ? "activated" : "deactivated"}.
wow, nice catch

2021-01-25 14:47 UTC, tiagoalvesdulce commented on teste2e/cypress/e2e/adminAccount.js
> +    cy.wait("@registerUser").its("status").should("eq", 200);
Instead of doing it manually you can call the API directly here, like I do with the command `login`. eg:

```
Cypress.Commands.add("login", (user) => {
  requestWithCsrfToken("api/v1/login", {
    email: user.email,
    password: sha3_256(user.password)
  });
});
```

This will speed up the tests. Don't worry because the manual registration will already be covered by the `register.js` tests.

2021-01-26 13:56 UTC, thi4go commented
Good catch mate, I was following the coordination issue so I missed those actions. I can add them in another PR, it that's ok. @tiagoalvesdulce

2021-02-02 13:58 UTC, tiagoalvesdulce commented
That's fine. Just resolve my comment and it will be good to go.

2021-02-07 17:26 UTC, thi4go commented
Done @tiagoalvesdulce :+1:

2021-02-10 15:53 UTC, tiagoalvesdulce approved these changes
Thanks!

2021-02-10 15:54 UTC, merged