tlog: pi adjustments for new tlog api
decred/politeiagui pull request #2306
Opened 2021-03-02 18:09 UTC by victorgcramos

This diff updates the pi app to use new tlog api specs. This description will still be updated.

### Solution description

> Describe your code changes for reviewers. Explain your code changes and how does it solve the issue described

_Example:_ This diff adds a new provider to handle the mentioned issue, so user can access it by using the new `useFeature()` hook, which implements the method A. Reference: [reference_link]()

### Dependencies
Depends on https://github.com/decred/politeia/pull/1180

2021-03-02 19:18 UTC, lukebp commented
Current gui issues

- [x] error handling needs to be fixed
- [x] editing an unvetted proposal doesn't reflect the edit until you reload the
    page
- [x] clicking back to a different proposal version is broken. The pi /proposals
     route is only for fetching the data required to display the list views. It
     doesn't return all of the files. You should be using the record /details
     route.
- [x] navigating to a single comment thread then clicking the "view all" button
     is broken
- [x] abandoned proposals are not showing up in the list views. Keep in mind
     that the record inventory route groups them by record status and the
     record status for abandoned proposals is going to show up as "archived".
     Abandoned is terminology that is specific to the proposal system so it
     won't be present in the generic /records routes.
- [x] all github links need to be taken out. These don't exist anymore.
- [x] failed login attempts alignment is bad
- [x] number of comments are not being shown in the list views
- [x] remove proposal list view tab numbering
- [x] approved tag is showing as missing
- [x] i'm not seeing the "censor" button anywhere when looking at the unvetted
     proposal list view or the proposal details
- [x] the backend doesn't allow a user to upvote/downvote their own comment. The
     gui shouldn't allow them to either.
- [x] submit a proposal, go to the user details page to try and find the
     proposal in the user's proposal list. I get the error: `Error:
     PublicActions requires an PublicActionsProvider on a higher level of the
     component tree.` I was an admin, but I don't know if that matters.
     I get the same error when trying to view all unvetted proposals as an
     admin.
- [x] figure out list views
- [x] replace `Ineligible` tab with `Abandoned` and don't show vetted censored proposals
- [ ] rejected vote list items are messed up
- [ ] proposal vote timestamps need a download button and workflow
- [ ] proposal bundle contents needs to match a records API `Record`
- [ ] consistent naming convention among download files
- [ ] proposal URLs are still `/proposals`
- [ ] paginate the vote summaries request.  Ex. if I have 10 proposals being
  voted on the gui requests the vote summaries for all 10 at the same time.
  This leads to longer load times. The vote summaries request should be split
  up to whatever size the gui page size is.
- [ ] minor perf improvement, the unvetted list views don't need to check
     the vote summaries. They're not going to exist for unvetted proposals.

2021-03-02 22:10 UTC, victorgcramos commented
- [x] rejected vote list items are messed up
- [x] proposal URLs are still /proposals
- [x] minor perf improvement, the unvetted list views don't need to check
the vote summaries. They're not going to exist for unvetted proposals.

2021-03-12 17:47 UTC, tiagoalvesdulce reviewed
Left a few suggestions. Notice that the code has a lot of references to proposals, we should avoid it and use records instead.

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/DownloadJSON.jsx
> +    !(props[beforeDownload] instanceof Promise)
A better approach to verify if something is a `Promise` is by verifying if it has a `then` method. So I'ld replace this by `const isPromise = (obj) => obj && typeof obj.then === "function"`

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/ModalConfirm.jsx
> +      onClose={success ? onCloseSuccess || onClose : onClose}
this could be replaced by `success && onCloseSuccess ? onCloseSuccess : onClose` for clarity.

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/ModalStartVote/ModalStartVote.jsx
> +  getRoundedAverage(!min ? 1 : min, max),
why min is defaulted to `100` and then to `1` in the same context? IMO you can choose a single default value and use default params e.g `const getBlockDurationArray = (min = 100, max) => ...`

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/Proposal/ProposalActions.jsx
> +  const underDiscussion = isUnderDiscussionProposal(proposal, voteSummary);
should be renamed to `isUnderDiscussion`

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/ProposalForm/ProposalForm.jsx
> +        // Also, we use short prefix when navigating to propsoal page
We shouldn't refer to `proposal` anymore. You can use `record` instead

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/ProposalForm/ProposalForm.jsx
> +            isCreate
`isCreate` isn't descriptive enough. Maybe `isCreateRecordPage`?

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/RecordsView/RecordsView.jsx
> +    onFetchMoreProposals && onFetchMoreProposals();
Can we replace this by `handleFetchMoreRecords`?

2021-03-12 17:47 UTC, tiagoalvesdulce commented on src/components/VersionPicker/VersionPicker.jsx
> +const VersionPicker = ({ version, token, className, proposalState }) => {
recordState

2021-03-15 22:28 UTC, victorgcramos commented on src/components/ModalStartVote/ModalStartVote.jsx
> +  getRoundedAverage(!min ? 1 : min, max),
I used it just for test purposes. It shouldn't be there. Good catch!

2021-03-24 14:28 UTC, lukebp commented
Seeing some alignment issues on various parts of the app.  I'm using firefox on a 14'' screen.

- [ ] "Complete your registration" is off the screen
![image](https://user-images.githubusercontent.com/9039877/112325068-5df5ed00-8c81-11eb-897d-ffe7ad61c67d.png)

- [ ] Tx hash for user registration paywall
![image](https://user-images.githubusercontent.com/9039877/112324987-4e76a400-8c81-11eb-8457-5aea19cb751c.png)

- [ ] Tx hash for proposal credits
![image](https://user-images.githubusercontent.com/9039877/112325185-76fe9e00-8c81-11eb-891f-2d561969993a.png)

- [ ] Step 2 of the 2fa page says `Scan the QR Code with a TOTP Authenticator`.  Most users are not going to know what this is.  You should list some of the most popular TOTP apps so they know what you're talking about. For example, `Scan the QR Code with a TOTP Authenticator (Authy, Google Authenticator, YubiKey, etc)`

- [ ] The wrong 2fa error message never got fixed.

2021-03-30 20:01 UTC, tiagoalvesdulce approved these changes
I tested and it works great. Only a few minor code comments from my previous review were not addressed. We can open an issue to change all the references of proposals to records in a future PR but the other comments should be pretty easy to implement. Also, the tests are all broken. I'd like that at least the e2e tests are fixed before merging this PR. Please replace the `cy:open` script on `package.json` by this: `"cy:open": "cd teste2e && npm install && cypress open"`. I notice `npm install` wasn't running.

2021-03-30 20:03 UTC, tiagoalvesdulce requested changes
Changing to `request changes` for the e2e tests.

2021-03-30 20:15 UTC, victorgcramos commented on src/components/ProposalForm/ProposalForm.jsx
> +        // Also, we use short prefix when navigating to propsoal page
I think we could link it to a separate issue, as it seems to be a long diff.

2021-03-30 20:29 UTC, tiagoalvesdulce approved these changes
We discussed on matrix and decided to fix the tests in a future PR.

2021-03-30 20:31 UTC, merged