fix: make sure all vote data is consistent on redux state
decred/politeiagui pull request #2315
Opened 2021-04-03 20:15 UTC by thi4go

This diff makes sure that all vote data is loaded properly and consistent on our `proposalVotes` state when accessing the details of a proposal with an ongoing/finished vote.

2021-04-05 18:32 UTC, tiagoalvesdulce requested changes
LGTM, fix lint warns and should be good.

2021-04-05 22:05 UTC, victorgcramos approved these changes
LGTM!

2021-04-06 15:07 UTC, thi4go commented
@tiagoalvesdulce done mate

2021-04-07 14:21 UTC, tiagoalvesdulce approved these changes

2021-04-07 16:01 UTC, merged