[wip] Normalize redux state to use short tokens throughout the app
decred/politeiagui pull request #2365
Opened 2021-05-01 22:02 UTC by thi4go

This diff normalizes our entire redux state to use short tokens instead of full tokens, resolving various bugs that may happen when the app expects one token form, and receives another.

closes #2353

2021-05-01 23:28 UTC, amassarwi commented
@thi4go thanks for this mate, this should be closing #2351 I think.

2021-05-03 11:39 UTC, tiagoalvesdulce commented
We should wait for e2e to be ready before getting this in since it touches a lot of sensitive parts of the app

2021-05-12 18:43 UTC, tiagoalvesdulce commented
Closed by mistake

2021-05-12 20:54 UTC, thi4go commented
@tiagoalvesdulce e2e already being very useful. caught some minor bug that could otherwise pass unoticed on a review 👍 :)

this PR is ready

2021-05-13 12:57 UTC, tiagoalvesdulce commented
Nice! Can you run `yarn prettify`?

2021-05-17 13:32 UTC, tiagoalvesdulce requested changes
I ran prettify for thiago because his dev env was messed up.

While testing this I found several Issues. See:

Duplicated new proposal and proposal not showing on top of discussion tab:

https://user-images.githubusercontent.com/13955303/118496651-b3d39800-b6fa-11eb-86b2-5967042372cf.mp4

Wrong tabs:
<img width="768" alt="Screen Shot 2021-05-17 at 10 24 31" src="https://user-images.githubusercontent.com/13955303/118497023-0dd45d80-b6fb-11eb-8cbc-37496b3335d4.png">
<img width="1280" alt="Screen Shot 2021-05-17 at 10 25 01" src="https://user-images.githubusercontent.com/13955303/118497031-0f9e2100-b6fb-11eb-9319-4d383a6583f0.png">
<img width="1280" alt="Screen Shot 2021-05-17 at 10 25 18" src="https://user-images.githubusercontent.com/13955303/118497034-10cf4e00-b6fb-11eb-87e1-df49034e2e0c.png">
<img width="1280" alt="Screen Shot 2021-05-17 at 10 25 25" src="https://user-images.githubusercontent.com/13955303/118497043-13ca3e80-b6fb-11eb-919d-daa8a295e12a.png">

Voting proposal showing up at admin's unreviewed tab:

<img width="1278" alt="Screen Shot 2021-05-17 at 10 26 06" src="https://user-images.githubusercontent.com/13955303/118497146-2f354980-b6fb-11eb-8b2f-96e408c9fbea.png">

2021-05-17 14:33 UTC, thi4go commented
Thanks for the review @tiagoalvesdulce, nice catch. Will be fixing this asap

2021-05-25 21:39 UTC, tiagoalvesdulce commented
I think the sorting is still messed up in the "In Discussion" tab. I don't know if it's intentional but it's putting proposals with voting authorized on top of others:

<img width="776" alt="Screen Shot 2021-05-25 at 18 30 38" src="https://user-images.githubusercontent.com/13955303/119571324-9bf9b500-bd87-11eb-82ea-b503383564e7.png">

The proposal "sssssss" was created after the proposal "oooooooooo".

2021-05-26 13:27 UTC, tiagoalvesdulce requested changes
Sorting is working as expected now.

Seeing this error when trying to submit an edited proposal:

<img width="820" alt="Screen Shot 2021-05-26 at 10 21 48" src="https://user-images.githubusercontent.com/13955303/119667210-7498fb80-be0c-11eb-8823-3c71434f493b.png">

Is the endpoint expecting the full token?

2021-05-26 13:27 UTC, tiagoalvesdulce commented on src/components/RecordsView/RecordsView.jsx
> +  console.log(filteredRecords);
log

2021-05-26 13:45 UTC, tiagoalvesdulce approved these changes
LGTM

2021-05-26 14:00 UTC, merged