Change link color to light green when the website is in dark mode
decred/politeiagui pull request #2407
Opened 2021-05-24 14:25 UTC by vibros68

Resolve #2300

Light mode preview
![proposal_link_light_mode](https://user-images.githubusercontent.com/84569563/119361677-208bfb00-bcd6-11eb-8e54-ddf3a3ef1a6a.png)

Dark mode preview 
![proposal_link_dark_mode](https://user-images.githubusercontent.com/84569563/119361729-2e418080-bcd6-11eb-939a-10001b49088b.png)

There is another text color is user name. It musts be changed in anther repository (pi-ui)

2021-05-25 02:46 UTC, tiagoalvesdulce requested changes
As @MariaPleshkova said [here](https://github.com/decred/politeiagui/issues/2300#issuecomment-779867754) I think we should stick to blue for the links. Any new thoughts, Maria?

2021-05-25 02:46 UTC, tiagoalvesdulce commented on src/components/Markdown/styles.css
> +  color: #02ffa3;
We prefer to use CSS-variables for the colors, see: https://github.com/decred/pi-ui/blob/master/src/theme/darkTheme.js. Pi-ui css-variables are already imported into pgui so you can just use `color: var(--color-primary)`, for example.

2021-05-25 03:52 UTC, vibros68 commented on src/components/Markdown/styles.css
> +  color: #02ffa3;
Hi @tiagoalvesdulce . I changed as your request. Please take a look

2021-05-25 03:56 UTC, vibros68 commented on src/components/Markdown/styles.css
> +  color: #02ffa3;
There is an var. That is `--color-primary-dark` .But  I did not pick it because it is grey. It  is not good to see too. So I pick `--color-green`

2021-05-26 16:03 UTC, MariaPleshkova commented
> As @MariaPleshkova said [here](https://github.com/decred/politeiagui/issues/2300#issuecomment-779867754) I think we should stick to blue for the links. Any new thoughts, Maria?

Let's keep them blue `#2970FF` for now.

Link color is still `#0366d6` on proposals.decred.org :
![image](https://user-images.githubusercontent.com/8841018/119693035-95853f00-be54-11eb-9776-a58922c56163.png)

`#2970FF`(one of our accent colors from the palette) is a bit brighter:
![image](https://user-images.githubusercontent.com/8841018/119693102-a5048800-be54-11eb-97b0-ada6dc27794a.png)

2021-05-27 02:53 UTC, skynet0590 commented
> > As @MariaPleshkova said [here](https://github.com/decred/politeiagui/issues/2300#issuecomment-779867754) I think we should stick to blue for the links. Any new thoughts, Maria?
> 
> Let's keep them blue `#2970FF` for now.
> 
> Link color is still `#0366d6` on proposals.decred.org :
> ![image](https://user-images.githubusercontent.com/8841018/119693035-95853f00-be54-11eb-9776-a58922c56163.png)
> 
> `#2970FF`(one of our accent colors from the palette) is a bit brighter:
> ![image](https://user-images.githubusercontent.com/8841018/119693102-a5048800-be54-11eb-97b0-ada6dc27794a.png)

Thank you

2021-05-28 12:16 UTC, tiagoalvesdulce approved these changes
LGTM. Thanks for your first contribution @vibros68 !

2021-05-28 12:47 UTC, vibros68 commented
Thank you

2021-06-08 00:21 UTC, tiagoalvesdulce commented
@vibros68 can you rename this PR since we decided to go with a brighter blue instead of light green?

2021-06-08 00:37 UTC, tiagoalvesdulce commented
Hey @MariaPleshkova I did some research in accessibility/color contrast and google chrome dev tools has a pretty good tool to debug this.

The contrast between our links with `#2970FF` and the background is 2.8, which is considered low. Refer to [this article](https://web.dev/color-and-contrast-accessibility/?utm_source=devtools) for more details.

<img width="232" alt="Screen Shot 2021-06-07 at 21 28 11" src="https://user-images.githubusercontent.com/13955303/121104170-d0ce2900-c7d7-11eb-9872-0e947270acb8.png">

Ideally we would increase this contrast ratio. Can we do something about it?

2021-06-23 21:30 UTC, MariaPleshkova commented
@tiagoalvesdulce hmm, yeah, maybe it's better to change `#2970FF` then. But I think that using the `#2ED8A3` green is also not a good idea, because we use it for another kind of elements like a tab stroke, field color when entered data is valid, etc. So, I guess we have to add one more color to the palette. I played around with the tool and ended up with lighter blue `#56A4FF`. 
![image](https://user-images.githubusercontent.com/8841018/123169727-53b2dd00-d482-11eb-9ac0-d8541bdd4677.png)
The contrast ratio while using this color is 4.5. AA is good, but AAA is not. I didn't find any appropriate color during the use of which AAA is ok. So, maybe one good index is enough?
![image](https://user-images.githubusercontent.com/8841018/123170456-36324300-d483-11eb-9d4c-ecc817d252fb.png)

2021-06-24 14:08 UTC, tiagoalvesdulce commented
`#56A4FF` Looks good. @vibros68 can you add this color to https://github.com/decred/pi-ui and make that the default color for all our links on dark theme?

2021-07-13 08:57 UTC, vibros68 commented
I am sorry because have not followed the discussion I will do it now

2021-07-13 10:51 UTC, vibros68 commented
@tiagoalvesdulce If I create a new variable for the new color. I will need to add some more css on politeiagui. Or if I just change the value of the old variable (color-primary) to `#56A4FF` I will don't need to change  any css on politeiagui but the color will effect other element like the buttons. You can see the picture
![Screenshot from 2021-07-13 17-49-43](https://user-images.githubusercontent.com/84569563/125439735-4a0f436b-ab59-4837-aecf-05c463116302.png)

2021-07-13 11:28 UTC, tiagoalvesdulce commented
You can create a new variable on lightTheme (https://github.com/decred/pi-ui/blob/master/src/theme/lightTheme.js) called `link-color` and assign `color-primary` to it. Then, you go to the darkTheme (https://github.com/decred/pi-ui/blob/master/src/theme/darkTheme.js) create a variable with the same name (`link-color`) and override it with `#56A4FF`. Now you just have to go to the places we style links and change the color. Keep in mind that to work with `pi-ui` you have to know [yarn links](https://classic.yarnpkg.com/en/docs/cli/link/)

2021-07-13 11:36 UTC, vibros68 commented
Thank you. yarn link is exactly what I need at the moment

2021-07-14 12:03 UTC, vibros68 commented
The last commit will work after [pi-ui/pull/343](https://github.com/decred/pi-ui/pull/343) being merged

2021-07-14 13:50 UTC, tiagoalvesdulce commented
Now that https://github.com/decred/pi-ui/pull/343 is in, can you upgrade pi-ui? I like to run upgrade-interactive and upgrade only pi-ui. See: https://classic.yarnpkg.com/en/docs/cli/upgrade-interactive/

2021-07-16 13:45 UTC, tiagoalvesdulce commented
I fixed a small issue on https://github.com/decred/pi-ui/pull/351, can you upgrade pi-ui again?

2021-07-16 14:39 UTC, vibros68 commented
Okay

2021-07-18 03:45 UTC, vibros68 commented
@tiagoalvesdulce should this PR be merge?

2021-07-19 11:23 UTC, tiagoalvesdulce approved these changes
LGTM

2021-07-19 11:24 UTC, merged

2021-07-19 11:50 UTC, vibros68 commented
Thank you