2070 how long it takes to update proposal credit balance
decred/politeiagui pull request #2417
Opened 2021-06-03 07:48 UTC by vibros68

Close #2070 

### Solution description

return MinConfirmationsRequired from politeiawww
[pull request here](https://github.com/decred/politeia/pull/1423)
to show how many confirmations needed

Make the paywall pool request be unlimited to picking up the transaction immediately

### UI Changes Screenshot

![Screenshot from 2021-06-02 10-37-17](https://user-images.githubusercontent.com/84569563/120604097-e27d9c80-c476-11eb-9476-7c652c4b3e35.png)

2021-06-03 12:41 UTC, victorgcramos requested changes
Hey @vibros68! Thanks for the PR. Left some inline comments.

I'd recommend you to rename this PR here, and try to follow the naming pattern we use in this repo.

Also, your PR depends on another PR of our repo, so it's better for you to indicate it as:

Depends on https://github.com/decred/politeia/pull/1423

2021-06-03 12:41 UTC, victorgcramos commented on src/containers/User/Detail/Credits/components/CreditHistorySection.jsx
> +import usePolicy from "../../../../../hooks/api/usePolicy";
you can replace this relative path to "src/hooks/api/usePolicy". This is the pattern for politeiagui.

2021-06-03 12:41 UTC, victorgcramos commented on src/containers/User/Detail/Credits/components/CreditHistorySection.jsx
> +  const policy = usePolicy();
```suggestion
  const { policy } = usePolicy();
```
A good way to avoid the redundant `policy.policy.minconfirmationsrequired` prop access 😁. Unless your destruction gets too big, please use object destruction.

2021-06-03 12:41 UTC, victorgcramos commented on src/containers/User/Detail/Credits/helpers.js
> +    <StatusTag type="bluePending" text={`Waiting for confirmations(${purchase.confirmations}/${purchase.minRequiredConfirmations})`} />
what about adding some space or padding before the first parenthesis?
```suggestion
    <StatusTag type="bluePending" text={`Waiting for confirmations (${purchase.confirmations}/${purchase.minRequiredConfirmations})`} />
```

2021-06-03 16:04 UTC, vibros68 commented
> Hey @vibros68! Thanks for the PR. Left some inline comments.
> 
> I'd recommend you to rename this PR here, and try to follow the naming pattern we use in this repo.
> 
> Also, your PR depends on another PR of our repo, so it's better for you to indicate it as:
> 
> Depends on [decred/politeia#1423](https://github.com/decred/politeia/pull/1423)

Hi @victorgcramos . Thank you because reviewed my PR. It is great for me . I did some fix follow your request

2021-06-03 16:20 UTC, lukebp commented
The `Waiting for confirmations (0/2)` is pretty lengthy and wide.  Might something like `Pending (0/2 confirmations)` be cleaner?

2021-06-08 15:10 UTC, victorgcramos commented
Hey, you forgot do fix what I've mentioned before, @vibros68!

> I'd recommend you to rename this PR here, and try to follow the naming pattern we use in this repo.
   Also, your PR depends on another PR of our repo, so it's better for you to indicate it as: 
   Depends on decred/politeia#1423

2021-06-09 01:41 UTC, vibros68 commented
> Hey, you forgot do fix what I've mentioned before, @vibros68!
> 
> > I'd recommend you to rename this PR here, and try to follow the naming pattern we use in this repo.
> > Also, your PR depends on another PR of our repo, so it's better for you to indicate it as:
> > Depends on [decred/politeia#1423](https://github.com/decred/politeia/pull/1423)

Hi @victorgcramos . I made some changes in the name and description of the PR. Also change variable name. May be it is better. I hope you can do review again. Thanks

2021-06-09 16:32 UTC, victorgcramos approved these changes
LGTM

2021-06-11 01:29 UTC, tiagoalvesdulce approved these changes
ACK

2021-06-11 01:32 UTC, merged