Remove unnecessary duplicate requests
decred/politeiagui pull request #2422
Opened 2021-06-09 04:54 UTC by vibros68

Closed #2403 

### Solution description

The cause of the bug is the value of `unfetchedTokens` is wrong after the first time calculating when `proposals` is not updated yet since it is stored in redux. So I add the `fetchedProposals` at that moment to be calculated 

### Screen shot

![Screenshot from 2021-06-09 11-44-33](https://user-images.githubusercontent.com/84569563/121295510-602f2580-c919-11eb-9d9b-a8c86e6185f7.png)

2021-06-09 17:07 UTC, victorgcramos approved these changes
LGTM! Good job!

2021-06-11 01:06 UTC, tiagoalvesdulce requested changes
Testing it I still see duplicate requests. See:

First request (uses full tokens):
<img width="668" alt="Screen Shot 2021-06-10 at 21 59 31" src="https://user-images.githubusercontent.com/13955303/121615499-6e736380-ca37-11eb-9a54-5123a7e49bdd.png">

Second request (uses short tokens - and one full token):
<img width="666" alt="Screen Shot 2021-06-10 at 21 59 47" src="https://user-images.githubusercontent.com/13955303/121615590-a084c580-ca37-11eb-8c0c-f475a9764353.png">

Notice it is fetching 3 of the 4 proposals fetched in the first request again but now with short tokens.

I suggest that you test your PR with multiple proposals, might help to debug this.

2021-06-11 02:29 UTC, vibros68 commented
Hi @tiagoalvesdulce . I tested with 5 proposals and the code seems be looking fine for me
![Screenshot from 2021-06-11 09-28-39](https://user-images.githubusercontent.com/84569563/121622058-837fdf00-ca97-11eb-8ee6-128b2a28fc77.png)
![Screenshot from 2021-06-11 09-28-54](https://user-images.githubusercontent.com/84569563/121622063-8549a280-ca97-11eb-9f14-e3425ca185ff.png)

2021-06-11 02:31 UTC, vibros68 commented
My both requests are using long token

2021-06-11 12:25 UTC, victorgcramos commented
@vibros68 A good practice is to test with more than 20 proposals, so you can handle the pagination properly

2021-06-11 14:50 UTC, tiagoalvesdulce commented
You are right, @vibros68. Turns out my backend was messed up and the proposals inventory was returning old proposals I had. This PR is good to go.

2021-06-11 14:50 UTC, tiagoalvesdulce approved these changes
tACK

2021-06-11 14:50 UTC, merged

2021-06-12 02:59 UTC, vibros68 commented
@tiagoalvesdulce @victorgcramos 
The same result with 21 items

https://user-images.githubusercontent.com/84569563/121763232-8b598500-cb64-11eb-8946-746ffcd409d8.mp4