Download bundle UX improvement
decred/politeiagui pull request #2453
Opened 2021-06-22 10:00 UTC by vibros68

resolved #2438 

### Description

adjust download bundle: show loading wheel while the data is being fetched; show progress for paginated downloads only when there are more than 1 page

2021-06-22 15:45 UTC, lukebp commented
This doesn't appear to be updating the % complete correctly.


https://user-images.githubusercontent.com/9039877/122956599-c323b200-d346-11eb-808c-d47bf0cd12e7.mp4

You can use the `pictl seedproposals [adminEmail] [adminPassword]` command to seed your backend with proposals that contain 150 comments each.

2021-06-22 19:04 UTC, vibros68 commented
I fixed it. Sorry about that

2021-06-22 19:04 UTC, vibros68 commented
I fixed it. Sorry about that

2021-06-22 19:19 UTC, lukebp requested changes
1. I'm seeing a `ticketvote/v1/details` request being made when you load the proposal details page.  This is a expensive route and should only be retrieved when the votes bundle is being downloaded.
2. Downloading the votes bundle does not download the actual cast votes.

2021-06-22 19:19 UTC, lukebp commented on src/containers/Comments/Download/hooks.js
> +        ? ((Object.keys(timestamps).length * 100) / commentsLength).toFixed(2)
I don't think we need to show decimal places on these % complete indicators.  Instead of `66.67%`, lets just show `67%`.

2021-06-28 20:52 UTC, victorgcramos requested changes
Hey @vibros68, thanks for the PR. Left some inline comments in addition to luke's review.

2021-06-28 20:52 UTC, victorgcramos commented on src/containers/Comments/Download/DownloadCommentsTimestamps.jsx
> +      {multiPage ? <span style={{ marginRight: 10 }}>{progress}%</span> : <></>}
```suggestion
      {multiPage && <span style={{ marginRight: 10 }}>{progress}%</span>}
```

2021-06-28 20:52 UTC, victorgcramos commented on src/containers/Proposal/Download/DownloadVotesTimestamps.jsx
> +      {multiPage ? <span style={{ marginRight: 10 }}>{progress}%</span> : <></>}
```suggestion
      {multiPage && <span style={{ marginRight: 10 }}>{progress}%</span> }
```

2021-06-28 20:52 UTC, victorgcramos commented on src/containers/Comments/Download/DownloadCommentsTimestamps.jsx
> +    </div>
Wrapping this inside a `<div>` element creates an odd alignment on the download progress. See:

<img width="163" alt="Screen Shot 2021-06-28 at 5 37 10 PM" src="https://user-images.githubusercontent.com/22639213/123700941-8c163a80-d837-11eb-82e9-b50eb32e65fa.png">

2021-06-29 18:01 UTC, lukebp commented
> A ticketvote/v1/details request is being made when you load the proposal details page. This is a expensive route and should only be retrieved when the votes bundle is being downloaded.

This is an issue on master.  It was not introduce by this pull request.  Please disregard this comment.

2021-06-29 20:35 UTC, lukebp commented
Two pre-existing bugs were discovered during review of this pull request. #2460 and #2461.

This pull request does not need to fix 2460, but it should assume that the vote details call is being removed and should not rely on the vote details being available prior to download. 2461 should be fixed in this pull request.  

To accomplish both of these it should:

1. Retrieve the vote details when the `Votes Bundle` button is clicked.
2. Retrieve the vote results when the `Votes Bundle` button is clicked.
3. Populate the `Votes Bundle` correctly with the retrieved data.

2021-06-30 15:52 UTC, vibros68 commented on src/containers/Comments/Download/DownloadCommentsTimestamps.jsx
> +      {multiPage ? <span style={{ marginRight: 10 }}>{progress}%</span> : <></>}
Thank you

2021-07-05 19:30 UTC, victorgcramos requested changes
Progress percentage is till with a wrong alignment. It should be vertically centralized with the progress circle.

<img width="185" alt="Screen Shot 2021-07-05 at 4 28 34 PM" src="https://user-images.githubusercontent.com/22639213/124512140-161d5080-ddae-11eb-9752-4fd3bb351563.png">

2021-07-05 19:30 UTC, victorgcramos commented on src/components/RecordWrapper/RecordWrapper.jsx
> +  return <DownloadJSON fileName={fileName} label={label} content={bundle} />;*/
comment

2021-07-05 19:30 UTC, victorgcramos commented on src/components/RecordWrapper/RecordWrapper.jsx
>    };
comment

2021-07-06 16:42 UTC, lukebp requested changes
The UX is looking good.  See the comment about the server public key though.

2021-07-06 16:42 UTC, lukebp commented on src/actions/api.js
> +// Votes Bundle
The `serverpublickey` is missing from the votes bundle.

2021-07-06 17:12 UTC, vibros68 commented on src/actions/api.js
> +// Votes Bundle
I added

2021-07-06 17:20 UTC, lukebp requested changes
The votes bundle JSON has been changed from `details` to `detail`.  You can't make changes like this.  It breaks other software that expects `details`.  Please change it back.

![image](https://user-images.githubusercontent.com/9039877/124641575-7c5cae80-de54-11eb-80fc-efad95fd1560.png)

2021-07-06 17:35 UTC, vibros68 commented
I am sorry. It is fixed now

2021-07-06 17:46 UTC, lukebp approved these changes
tACK

This looks good from a UX standpoint. Verification using `politeiaverify` works as expected with all bundle downloads.

@tiagoalvesdulce and @victorgcramos will need to approve the code.

2021-07-08 12:33 UTC, tiagoalvesdulce approved these changes
LGTM

2021-07-09 13:47 UTC, victorgcramos approved these changes
LGTM!

2021-07-09 14:13 UTC, merged