fix: Improve censored proposals UX
decred/politeiagui pull request #2454
Opened 2021-06-23 13:08 UTC by thi4go

Closes #2440

### Solution description

Include new censored proposal render conditions on `Proposal.jsx`.  

### UI Changes Screenshot

Proposal List
![image](https://user-images.githubusercontent.com/2729122/123099348-7bfdf580-d408-11eb-8f59-d6639c3f4033.png)

Proposal Details
![image](https://user-images.githubusercontent.com/2729122/123100439-810f7480-d409-11eb-9d07-d903153909fa.png)

2021-06-23 13:39 UTC, lukebp commented
The list item cards appear to still be smaller than an abandoned list item, is that accurate?  If so, we want to make them the same size.  All list items cards should be the same size regardless of what list they're displaying.

2021-06-24 20:19 UTC, thi4go commented
@lukebp indeed, the comments icon on the abandoned proposals is giving a larger bottom padding versus the censored proposals. Will fix this before undrafting the PR

2021-06-28 21:04 UTC, lukebp approved these changes
ACK

UX looks good.

2021-06-28 22:23 UTC, victorgcramos requested changes
Hey @thi4go thanks for the PR. The censored proposals UX looks really good. Abandoned tab is now standardized, and all proposals cards from it are giving the user the correct highlight. Good job!

One thing I'd ask you to take a deeper look into is that the `useProposalsStatusChangeUser` should be loaded once the `proposals` are loaded properly.

Left some inline comments! Thank you.

2021-06-28 22:23 UTC, victorgcramos commented on src/hooks/api/useProposalsStatusChangeUser.js
> +  ).filter((pk) => pk && !resultsByPk[pk]);
```suggestion
  const unfetchedPublicKeys = flow(
    values,
    flatMap((prop) => (prop.status === status ? prop.statuschangepk : [])),
    uniq,
    filter((pk) => pk && !resultsByPk[pk])
  )(proposals);
```

I think you should go for a functional approach here

2021-06-28 22:23 UTC, victorgcramos commented on src/hooks/api/useProposalsStatusChangeUser.js
> +  if (!isEmpty(unfetchedPublicKeys) && state.status === "success") {
```suggestion
  if (hasUnfetchedPublicKeys && state.status === "success") {
```

2021-06-28 22:23 UTC, victorgcramos commented on src/helpers.js
> +    ),
same here :)

2021-06-28 22:23 UTC, victorgcramos commented on src/hooks/api/useProposalsStatusChangeUser.js
> +        return send(FETCH);
good job. Very clean!

2021-06-28 22:44 UTC, thi4go commented on src/hooks/api/useProposalsStatusChangeUser.js
> +  ).filter((pk) => pk && !resultsByPk[pk]);
It is using a functional composition approach, but yeah, I suppose we can use lodash's `flow` here to improve readability

2021-06-28 22:50 UTC, thi4go commented on src/helpers.js
> +          ),
Function composition and functional approach is the standard of the repo. I don't think we gain declaritiveness by adding a `byStatus` in this case, like we do in our redux store, a global state store which is accessed by a lot of different parts of the code. The function in scope is a helper to yet another helper, `parseRawProposal`, and is only ever used there. Even if we ever come to use the function elsewhere for parsing user metadata decoupled from a proposal, imo it is more readable and clean to write:

```
const usermds = parseUserPluginMetadata(proposal)
const statuschangemd =  usermds[proposal.status]
or
const censoredmd = usermds[PROPOSAL_STATUS_CENSORED]
```
instead of:

```
const usermds = parseUserPluginMetadata(proposal)
const statuschangemd =  usermds.byStatus[proposal.status]
or
const censoredmd = usermds.byStatus[PROPOSAL_STATUS_CENSORED]
```

Seems like added verbosity without much to gain for a simple helper function return, and not a state control object etc. @tiagoalvesdulce would be nice if you drop your thoughts on this before moving forward

2021-06-28 23:11 UTC, victorgcramos commented on src/helpers.js
> +          ),
> Even if we ever come to use the function elsewhere for parsing user metadata decoupled from a proposal, imo it is more readable and clean to write

I disagree. If you use this function to parse any user metadata, you'll need to read the whole function to know that this "2" is the record status. How am I supposed to know that these numeric keys are about the status?

2021-06-28 23:15 UTC, thi4go commented on src/hooks/api/useProposalsStatusChangeUser.js
> +  if (!isEmpty(unfetchedPublicKeys) && state.status === "success") {
done

2021-06-28 23:19 UTC, thi4go commented on src/hooks/api/useProposalsStatusChangeUser.js
> +    : proposals;
Good match mate, no need for this check here

2021-06-28 23:24 UTC, thi4go commented on src/helpers.js
> +    ),
Not sure I follow. You mean using `flow` here?

2021-06-28 23:25 UTC, victorgcramos commented on src/helpers.js
> +    ),
comment went out of order. This is about the "byStatus" suggestion.

2021-06-29 00:01 UTC, victorgcramos commented on src/hooks/api/useProposalsStatusChangeUser.js
> +  ).filter((pk) => pk && !resultsByPk[pk]);
it's a matter of taste for me. Both will work!

2021-06-29 13:37 UTC, thi4go commented on src/hooks/api/useProposalsStatusChangeUser.js
> +  ).filter((pk) => pk && !resultsByPk[pk]);
checked and we can't use flow in this situation because `flatMap` and `filter` are native prototype Array methods, so they need to be called by an object of type Array, or we get `flatMap` and `filter` are not defined.

2021-06-29 13:51 UTC, thi4go commented
@victorgcramos comments addressed. The `useProposalsStatusChangeUser` is already doing this actually. It only starts the fetch machine once we have `unfetchedPublicKeys` set up, which only happens when the proposals batch are properly loaded and passed down to this hook. Otherwise, the fetch machine stays on the resolved state since there are no pk's to search for and no work to be done.

2021-06-29 22:08 UTC, victorgcramos approved these changes
tACK!

2021-07-08 12:37 UTC, tiagoalvesdulce commented
Seeing this error in the proposal details page:

<img width="1280" alt="Screen Shot 2021-07-08 at 09 35 38" src="https://user-images.githubusercontent.com/13955303/124922582-02e9cb00-dfd0-11eb-9dfd-281a42156798.png">

2021-07-08 12:37 UTC, tiagoalvesdulce requested changes
See comment above.

2021-07-08 12:53 UTC, victorgcramos commented
my fault. Forgot to check for undefined values on my code suggestion. Sorry guys.

2021-07-08 23:02 UTC, thi4go commented
@tiagoalvesdulce fixed mate

2021-07-14 12:48 UTC, tiagoalvesdulce requested changes
As listed on https://github.com/decred/politeiagui/issues/2450, the abandoned and censored cards should have the same height. Currently, they are different. See:

<img width="679" alt="Screen Shot 2021-07-14 at 09 44 29" src="https://user-images.githubusercontent.com/13955303/125624471-11c38e74-956d-4ae7-aed8-65aa8231c9fd.png">

<img width="678" alt="Screen Shot 2021-07-14 at 09 44 17" src="https://user-images.githubusercontent.com/13955303/125624496-3c07fa39-c7fe-4518-b792-05f808676845.png">

2021-07-14 12:55 UTC, victorgcramos commented
@tiagoalvesdulce I think that's because proposal title has this line break due to a small screen width, while censored proposals will only display its token, which is shorter. I don't think there's a way to avoid it consistently... Maybe the only thing that could be done in this case, is to have the same title boundaries for every proposal regardless its status tag. Any thoughts?

2021-07-14 13:08 UTC, tiagoalvesdulce commented
You're right, I picked a bad example. It's consistent between 1 line and 2 lines titles. We can discuss if we want to break the line or just put a `...` to it in a new issue if the difference in height create issues in the future. This PR LGTM.

2021-07-14 13:08 UTC, tiagoalvesdulce approved these changes

2021-07-14 13:09 UTC, merged