[wip] Proposal submission: Add additional proposal metadata.
decred/politeiagui pull request #2469
Opened 2021-07-08 19:40 UTC by amassarwi

Closes #2459.

2021-07-08 19:41 UTC, amassarwi commented on src/components/ProposalForm/ProposalForm.jsx
> +  console.log({ amountmin, amountmax, enddatemax, domains });
grrrrr

2021-07-08 21:38 UTC, amassarwi commented on src/components/ProposalForm/validation.js
> +
if both start & end dates are provided, ensure start date is smaller.

2021-07-17 16:11 UTC, amassarwi commented on package.json
> +    "pi-ui": "https://github.com/amassarwi/pi-ui#datepickerange",
will be reverted when https://github.com/decred/pi-ui/pull/352 is in.

2021-07-17 16:11 UTC, amassarwi commented on yarn.lock
> +"pi-ui@https://github.com/amassarwi/pi-ui#datepickerange":
same

2021-07-20 15:50 UTC, lukebp requested changes
The input box should start with $.  A $ should also be added to the invalid amounts.  Numbers should not be displayed without a unit.

![image](https://user-images.githubusercontent.com/9039877/126354134-97e0bdbb-ca9a-4cc0-99fc-825452fe76ea.png)

What's the purpose of putting the start date and end date in the same input box?  This seems like a worse UX for the date picker.  It doesn't appear that you can even choose an end date on mobile.

![image](https://user-images.githubusercontent.com/9039877/126355191-bdad9698-c9bb-4eb6-a1a9-178f6a7f2efe.png)

![image](https://user-images.githubusercontent.com/9039877/126355148-87bc51e0-de45-4615-afd1-30bbd72a699b.png)

2021-07-20 17:26 UTC, amassarwi commented
@lukebp you need to run `yarn install` to get latest datepicker version, all this weird bugs were fixed in https://github.com/decred/pi-ui/pull/352

2021-07-20 21:42 UTC, victorgcramos requested changes
Hey @amassarwi, thanks for the PR. This is working as expected regarding the data submission. Metadata is submitted correctly, editing is nice. I think we could improve the UX in 2 aspects:
1. The `Amount` field label should describe that the amount is in USD like `Amount (USD)` or something, and it shouldn't accept non-numeric values. See:
    <img width="1778" alt="Screen Shot 2021-07-20 at 6 22 35 PM" src="https://user-images.githubusercontent.com/22639213/126397884-a3e92098-c9b0-4168-a135-1f5ee8858282.png">

2. I think we could display the metaadata info on the proposals detail page in order to bring a full transparency regarding it. We can only notice the new metadata value changes using the `pictl` CLI. Maybe below the proposal description field, what do you think?
    <img width="1778" alt="Screen Shot 2021-07-20 at 6 25 39 PM" src="https://user-images.githubusercontent.com/22639213/126397875-afb7be9f-b7cb-483c-add0-020a3c6f272b.png">

2021-07-20 21:42 UTC, victorgcramos commented on src/actions/api.js
> +  eDate,
can we go for a more declarative naming? This is very very minor, but I think that replacing it with the full name will bring a better readability.

2021-07-21 12:41 UTC, lukebp commented
I agree about displaying the metadata on the proposal details page.  Good point.

2021-07-27 14:04 UTC, amassarwi commented on src/components/RecordWrapper/RecordWrapper.jsx
> +    !!amount &&
this condition is wrong here - currently RFPs not displaying the domain metadata but they should. pushing a fix in sec.

2021-07-27 14:22 UTC, amassarwi commented on src/components/RecordWrapper/RecordWrapper.jsx
> +    !!amount &&
fixed 👍🏽

2021-07-27 16:23 UTC, lukebp requested changes
I'm getting this error when I click the "New Proposal" button.

![image](https://user-images.githubusercontent.com/9039877/127191042-b13a2c6e-48df-4786-8198-b06059ff5c50.png)

2021-07-27 16:26 UTC, lukebp commented
Also, please update the original PR message with more details about what this PR does.  I should be able to fully understand all the changes being made by reading the message.

2021-07-27 17:57 UTC, lukebp requested changes
This is looking good from a UX standpoint.  Nice work.  I only have a few minor UX nits.

1. Can we add commas to the amount anytime its displayed to the user (amount error message, proposal details amount field)?  Displaying large amounts without commas make them hard to read. 

2. Can the `$` in the amount text box show up all the time instead of only after the first number is input.

3. Can we display the proposal metadata before the proposal text instead of after.  The metadata gives high level details that you would want to know before diving into the specifics of the proposal text.

2021-07-27 19:16 UTC, amassarwi commented
@lukebp 

Thanks for the review will do, regarding 2 not sure if that's a good ux as it would replace the field label and users will see
`$` as value instead of the `Amount (USD)` label we currently have. another option would be changing the label to
`Amount ($)` what do you think ?

2021-07-27 20:04 UTC, lukebp commented
@amassarwi that makes sense.  The part that find weird is the transition from when the cursor has the input box selected (no $ at this point) to when the user inputs a number and the $ gets added.  There's movement in there that is not smooth.  Try it out and see if you can spot it.

Do you think it would make sense to add the $ once the cursor selects the input box instead of when the user inputs the first number?

2021-07-27 20:28 UTC, amassarwi commented
@lukebp I see what you mean, adding the `$` unit on focus is a good i can give it a try and we see how it looks like.

2021-07-27 21:03 UTC, victorgcramos approved these changes
LGTM! Good job! 🚀

2021-07-28 14:38 UTC, amassarwi commented
@lukebp 
 
1 & 3 addressed; working on 2.

2021-07-28 18:10 UTC, lukebp commented
UX looks good.  One last edge case.  How do you think this should be handled?  User inputs the amount with commas.
![image](https://user-images.githubusercontent.com/9039877/127374030-9ad240cf-9c85-4170-917c-20fdf7d8e74b.png)

2021-07-28 19:40 UTC, lukebp commented
tACK

UX looks good.

2021-07-29 21:31 UTC, lukebp requested changes

2021-07-29 21:31 UTC, lukebp commented on src/components/DatePickerField/DatePickerField.jsx
> +const DatePickerField = ({
A minimum start date policy is being added to the backend.  The date picker will need to take this into account for the start and end dates.

2021-07-30 11:51 UTC, amass01 commented on src/components/DatePickerField/DatePickerField.jsx
> +const DatePickerField = ({
done 👍🏽

2021-07-30 12:50 UTC, lukebp approved these changes
tACK

Needs a final code review from @tiagoalvesdulce.

2021-07-30 14:01 UTC, tiagoalvesdulce reviewed
Looking good. Great job. Left a few comments.

2021-07-30 14:01 UTC, tiagoalvesdulce commented on teste2e/cypress/utils.js
> -  ]
Why can we get rid of this?

2021-07-30 14:24 UTC, amass01 commented on teste2e/cypress/utils.js
> -  ]
I think this is legacy code, the new proposal route accepts only files array and no metadata - see the one in api.js.

2021-07-30 14:45 UTC, tiagoalvesdulce commented on teste2e/cypress/utils.js
> -  ]
ok, cool.

2021-07-30 17:11 UTC, tiagoalvesdulce approved these changes

2021-07-30 17:49 UTC, merged