fix: Persist public data on the proposals state tree on logout
decred/politeiagui pull request #2479
Opened 2021-07-17 20:49 UTC by thi4go

This diff persists public data from the proposals state tree on user logout event.

closes #2474

2021-07-19 11:27 UTC, tiagoalvesdulce requested changes
You have some lint issues.

2021-07-19 11:44 UTC, tiagoalvesdulce requested changes
You also have an error:

<img width="1280" alt="Screen Shot 2021-07-08 at 09 35 38" src="https://user-images.githubusercontent.com/13955303/126155024-15fd9c7b-f602-46b3-a2f9-3459b1dba161.png">

To repro: login > go to vetted props > logout > login again > go to admin props

2021-07-19 14:07 UTC, thi4go commented
Hey @tiagoalvesdulce, pushed the lint fix. I think your local repo might be out of sync with this branch/masters. The `unfetchedPublicKeys` on this branch/master contains the correct undefined error handling for that case. It is as follows:

```
const unfetchedPublicKeys = flow(
    Object.values,
    flatMap((prop) => (prop?.status === status ? prop.statuschangepk : [])),
    uniq,
    filter((pk) => pk && !resultsByPk[pk])
  )(proposals);
```

The error path you described tho did indeed error out, good call. I removed an unnecessary clean for the proposals state tree that caused this error.

2021-07-21 12:05 UTC, tiagoalvesdulce approved these changes
tACK

2021-07-21 12:07 UTC, merged