feat: comment vote optimistic updates
decred/politeiagui pull request #2520
Opened 2021-08-07 01:39 UTC by victorgcramos

This diff closes #2517, an issue that requested the implementation of optimistic updates on comment vote actions.

### Solution description
In order to apply the optimistic updates on comment vote actions with redux, the state tree must be updated before the response from server gets returned. So, to handle possible errors, the previous comment count should also be stored on the state tree, so we can undo the changes we made. Therefore, when the server returns an error, the state is replaced by the backup, then the error is displayed.

### UI Changes Screenshot

Preview for offline mode errors:
![2517-comment-vote-highlight](https://user-images.githubusercontent.com/22639213/128583940-e1c0b2b3-ca6c-479b-953d-a9633b71e056.gif)

2021-08-09 12:25 UTC, lukebp approved these changes
ACK

2021-08-09 15:34 UTC, tiagoalvesdulce requested changes
https://user-images.githubusercontent.com/13955303/128732308-c0aee873-7873-4807-964b-48179f316f89.mp4

1. IMO we can remove the error message only if the next action succeeds. This flicker is a bit annoying. What do you think?
2. Since we are optimistically updating the button highlighting, we should do it for the number of votes as well. You can see that if we have a lot of comments, the delay is hurting the UX.

2021-08-09 16:17 UTC, lukebp commented
> This flicker is a bit annoying.

Good point.  Agreed.

> we should do it for the number of votes as well

Another good catch.  Agreed.

2021-08-10 20:54 UTC, victorgcramos commented
I added a new cache layer to comments likes, because it gets updated more frequently, and the comments array updates were expensive in terms of performance. This way we get an O(1) complexity instead of O(n).

You also might notice some delay on the count update in some cases in comparison to the 👍 highlighting. This happens because the hovering action highlights it, but if you move your cursor outside the 👍 box, you can test whether it gets optimistically updated.

2021-08-11 13:27 UTC, lukebp requested changes
I'm seeing this bug.  Upvote a comment.  Downvote the same comment.  The score is messed up.  This happens when going the other way as well (downvote then upvote).

![image](https://user-images.githubusercontent.com/9039877/129036933-ffabd757-e09b-479a-a228-9d2a342053eb.png)

A user is only allowed to change their vote preference 5 times.  Attempting to change it again results in this error.  This behavior is correct, but the error message needs to be human readable.

![image](https://user-images.githubusercontent.com/9039877/129037264-fd766dab-ae6b-4873-b2be-8a1bedf2cebf.png)

2021-08-11 14:55 UTC, victorgcramos commented
Okay, noticed that too. Already fixing it. My bad.

2021-08-12 00:38 UTC, victorgcramos commented
Tried to avoid all listed edge-cases. Also, added e2e tests for comment vote actions that simulates a delayed network, and error responses. Comment data is mocked, so we don't need to set it up before running tests.

2021-08-12 13:24 UTC, victorgcramos commented
it prevents multi clicking, which causes many edge-cases regarding optimistic updates

2021-08-12 13:33 UTC, lukebp commented
You think that's an acceptable UX?  Really?  Do any other major websites do that?  No, because it's a terrible UX.  Come on, this obvious stuff.  Fix it.

2021-08-12 13:40 UTC, lukebp commented
And when I say fix it, I don't just mean take the icon off and introduce edge cases that cause bugs.  Find a solution that has a good UX and that handles the edge cases properly.

2021-08-12 13:46 UTC, victorgcramos commented
ok...

2021-08-12 13:58 UTC, lukebp commented
I understand that I may be coming off a bit harsh, but we need to raise the bar for politeiagui development.  We are getting crushed by bugs and UX improvements that should have ever made it into the codebase the first time.  There's going to be a higher standard moving foward.

A simple question you can ask yourselve regarding UX changes is, how does reddit or twitter or github or the other major platforms do it?  They employ tons of UX people and designers.  Just copy what they do.  If we want to deviate, we can decide that at a later date once its already been implemented using the industry norm UX.

2021-08-12 14:11 UTC, tiagoalvesdulce approved these changes
The code is looking good. Victor only missed a small detail about debounced functions (they are quite tricky).

2021-08-12 14:11 UTC, tiagoalvesdulce commented on src/components/Likes/Likes.jsx
> +  };
This is probably breaking the debounce making you add the not-allowed cursor to prevent multiple clicks. The debounced function should be passed to the eventListener.

2021-08-12 14:12 UTC, victorgcramos commented on src/components/Likes/Likes.jsx
> +  };
yeah you're right! Thanks, mate!

2021-08-12 17:20 UTC, tiagoalvesdulce commented
LGTM

2021-08-12 18:10 UTC, lukebp approved these changes
Much better.  The UX is looking good.

tACK

2021-08-20 19:29 UTC, tiagoalvesdulce approved these changes
LGTM

2021-08-20 19:30 UTC, merged