Allow user to select diff versions
decred/politeiagui pull request #2524
Opened 2021-08-10 09:40 UTC by vibros68

closed #2466 

* **The old behavior is**: Click on version selector. Choose the version, the selector become loading cycle. After loaded will open a modal. 
* **The new behavior**: Click on the version selector, open the modal immediately, the loading indicator is inside the modal. after the data is fetched, will show the data. And when the user change the version we show the loading indicator again.

Preview:
![Screenshot from 2021-08-10 16-25-52](https://user-images.githubusercontent.com/84569563/128843221-b7a76bb9-f92f-4aa7-ba30-279fe4f58da2.png)

2021-08-12 13:34 UTC, lukebp commented
It's not just flickering.  The loading icons are also messed and the transitions are not smooth at all.

2021-08-14 08:26 UTC, vibros68 commented
https://user-images.githubusercontent.com/84569563/129439932-068b4def-6140-4378-9379-0088ad3bce36.mp4

The bug of flickering is exist in the master before. The cause is when change a state, react will re-render the modal instead of re-render the component inside the modal

2021-08-14 08:32 UTC, vibros68 commented
The bug of flickering is exist in the master before. The cause is when change a state, react will re-render the modal instead of re-render the component inside the modal

https://user-images.githubusercontent.com/84569563/129440100-2d8b91dc-a00d-445d-8438-3faf2cedbe3d.mp4

2021-08-14 13:26 UTC, vibros68 commented
The flickering is exist on master. I have opened a new issue for it: #2539 . I think it should be fixed on a separated pull request

2021-08-17 13:48 UTC, lukebp requested changes
Very nice.  The UX of this pull request is looking much better.

The one comment that I have is that I think we should have a header in the modal that explains what the modal does.  It might not be obvious to first time users.  I would add something similar to the github compare page.

![image](https://user-images.githubusercontent.com/9039877/129736892-418b327f-693e-43a8-94af-b26231ff4be5.png)

```
Compare versions
Compare changes across different versions of the record.
```

2021-08-18 17:15 UTC, lukebp requested changes
1. Can you add some more spacing in between the version dropdowns and the proposal title?  It's too close together and looks weird.

![image](https://user-images.githubusercontent.com/9039877/129940964-7599b408-9b24-4845-a5e6-ad05c4a654bb.png)

2. I get the error `TypeError: baseProposal is undefined` when I select `version 1` from the proposal details dropdown (not the modal).  I would expect it to pull up the model with a `-` in the first version dropdown and `version 1` in the second version dropdown.  The diff would look like the existing behavior for a `version 1` on test-proposals.decred.org where the entire record is highlighted in green.

![image](https://user-images.githubusercontent.com/9039877/129941723-1b5890d4-700d-42fd-9d24-07614cc935ea.png)

3. I think that the `-` option that I listed in the comment above should be one of the options for the first version dropdown in the modal.  Example, when viewing the diff between `-` and `version 3` it will show the full record contents of `version 3` as being new (highlighted in green).  This will allow for users to not only view the diff between two separate versions, but also view the entire contents of a specific version if they want to.

2021-08-19 15:03 UTC, lukebp reviewed
tACK

UX is looking good.  This is ready for a code review @tiagoalvesdulce.

2021-08-19 15:17 UTC, amass01 reviewed
Left some minors, code looks good over all.

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/CompareVersionSelector.jsx
> +        {versionsOptions.map((v) => {
```suggestion
        {versionsOptions.map((v) => 
```

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/CompareVersionSelector.jsx
> +          return (
```suggestion
           (
```

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/CompareVersionSelector.jsx
> +                onClick={() => {
```suggestion
                onClick={() => 
```

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/DiffProposal.jsx
> +  return (
add an empty line above the return statement.

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/DiffProposal.jsx
> +              <JoinTitle className={"margin-top-s"} separatorSymbol={":"}>
```suggestion
              <JoinTitle className="margin-top-s" separatorSymbol=":">
```

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/DiffProposal.jsx
> +              <JoinTitle className={"margin-top-s"} separatorSymbol={":"}>
no need for `{}` when passing a string as a param.

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/DiffProposal.jsx
> +                          event={"abandoned"}
same

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/DiffProposal.jsx
> +                <JoinTitle separatorSymbol={"-"}>
same

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/DiffProposal.jsx
> +                        event={"abandoned"}
same

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/hook.js
> +  useEffect(() => {
add empty line

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/hook.js
> +  useEffect(() => {
add empty line

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/hook.js
> +  const changedVersion = (versionType, v) => {
add empty line

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/hook.js
> +  const fetchProposalVersions = useCallback(
add empty line

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/hook.js
> +  const onFetchProposalDetailsWithoutState = useAction(
i'd add also add empty line before declaring a function which is not a oneliner.

2021-08-19 15:17 UTC, amass01 commented on src/components/ModalDiff/hook.js
> +  return {
also here empty line before return

2021-08-19 17:49 UTC, victorgcramos requested changes
Hey @vibros68, thanks for the PR. This is working as expected. I have only one comment regarding the UX. I think the proposal title should be bigger, because it does not look like a title and looks like a simple bold text. Also, there should be something indicating that these two selectors are about comparing one **against** the other.

<img width="982" alt="Screen Shot 2021-08-19 at 2 46 06 PM" src="https://user-images.githubusercontent.com/22639213/130118453-7c6e10fa-57bf-47da-8b7b-e628a99b57b2.png">

Left come inline comments regarding the code readability.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/CompareVersionSelector.jsx
> +  const ZERO_VERSION_ALIAS = "----------";
You can put this outside the component. It's a constant, and this will cause the attribution to happen every render.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/hook.js
> +import { useState, useCallback, useEffect } from "react";
This file should be named `hooks.js` instead of `hook`. All hooks files are named in plural, so we should follow this standard.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/const.js
> +export const COMPARE = "compare";
Again, naming should follow our standards. Use `constants.js` instead of `const.js`

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/hook.js
> +import { getAttachmentsFiles, parseRawProposal } from "../../helpers";
```suggestion
import { getAttachmentsFiles, parseRawProposal } from "src/helpers";
```

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/hook.js
> +export function useCompareVersionSelector(initVersion, latestVersion, token) {
`latestVersion` is never used. Either use it, or delete it.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/hook.js
> +    async (onFetchProposalDetailsWithoutState, token, version) => {
I think you don't to pass the `onFetchProposalDetailsWithoutState` function to the `fetchProposalVersions` func? I think you should pass the function to the `useCallback` deps instead of passing it every time you need to fetch a proposal version.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/hook.js
> +  ]);
The purpose of using the fetch machine is to avoid this multiple side effects handling. You have 4 possible states here, which could be used on the machine to improve the side-effects control. But, it's just my opinion. The way you did works fine.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/DiffProposal.jsx
> +      !compareLoading ? (
use a new variable that is more declarative when you have lots of conditions to handle. Maybe `isDiffAvailable` or something like this.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/DiffProposal.jsx
> +                          baseProposal.details.abandonedat && (
same here for the long conditions. Move it to a separate variable so we can have a cleaner code.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/DiffProposal.jsx
> +                        compareProposal.details.abandonedat && (
long conditions

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/DiffProposal.jsx
> +              </JoinTitle>
these two children do the same stuff. The only difference is that one is for `baseProposal` and other is for `compareProposal`. Since it's always (and should always be) the same code, please move it to another separate component, so we can improve scalability and declarativeness of our code.

2021-08-19 17:49 UTC, victorgcramos commented on src/components/ModalDiff/CompareVersionSelector.jsx
> +  }, [latest]);
let's use this https://lodash.com/docs/4.17.15#rangeRight to be more declarative. Try to use lodash or lodash/fp methods as always as you can. Only use `for` loops when it requires a huge performance improvement, or when you are dealing with long and complex arrays.

2021-08-19 18:03 UTC, lukebp commented
> I think the proposal title should be bigger, because it does not look like a title and looks like a simple bold text.

This is something that I ok'd, but I can see your point.  To keep things simple, this formatting should match the list item formatting.

> Also, there should be something indicating that these two selectors are about comparing one against the other.

@victorgcramos is this a change that was introduced by this PR?  Seems like it's out of scope.

2021-08-19 18:10 UTC, victorgcramos commented
> @victorgcramos is this a change that was introduced by this PR? Seems like it's out of scope.

It's just a simple indicator, like an icon between these two selectors. Having an empty space between them bothers me a little. Should be an easy task. See:
<img width="982" alt="130118453-7c6e10fa-57bf-47da-8b7b-e628a99b57b2" src="https://user-images.githubusercontent.com/22639213/130121390-0276bc09-2f5d-4e5a-9de2-3b92053130d5.png">
(did this using the markup tool on Mac. Of course it can be improved, but it's just to illustrate my point)

What do you think? The images on the PR description included this icon, and it looks good IMO.

2021-08-19 18:13 UTC, victorgcramos commented on src/components/ModalDiff/hook.js
> +import { getAttachmentsFiles, parseRawProposal } from "../../helpers";
Also, the `../../redux` can be replaced by `src/redux`

2021-08-19 18:19 UTC, lukebp commented
@victorgcramos oh I misread your comment.  I thought you were refering to changing how the red/green diff is shown.  Yeah, the indicator is already there.  It's just requires decred/pi-ui#357 to be merged.

2021-08-19 18:30 UTC, victorgcramos commented on src/components/ModalDiff/DiffProposal.jsx
> +              </JoinTitle>
I mean, use a new generic component for both, instead of `crtl+c` and `ctrl+v`. Always avoid doing it. This is a bad practice in terms of maintainability.

2021-08-20 14:57 UTC, vibros68 commented
>I think the proposal title should be bigger, because it does not look like a title and looks like a simple bold text. 
> 

Hmm. I changed the proposal title to be smaller because now there the modal title. If there are 2 titles in a frame, it looks a little 
weird. So I think I should change it to be bigger than normal size but smaller than the main title. How do you think @victorgcramos

2021-08-20 19:27 UTC, victorgcramos approved these changes
LGTM! You forgot to remove some `useEffect` deps.

2021-08-20 19:27 UTC, victorgcramos commented on src/components/ModalDiff/hooks.js
> +    onFetchProposalDetailsWithoutState
You forgot to remove it.

2021-08-20 19:27 UTC, victorgcramos commented on src/components/ModalDiff/hooks.js
> +    onFetchProposalDetailsWithoutState
same.

2021-08-21 12:00 UTC, vibros68 commented
@amass01 Can you do the further review?

2021-08-23 13:38 UTC, tiagoalvesdulce requested changes
I'm seeing some weird behavior when I play a little bit with the versions selected. In a proposal with 2 versions, if I select to compare the "base version" (empty) against the version 1, I can't go back and compare it against the version 2 if I don't close the modal.

Here is a video with steps to repro:

https://user-images.githubusercontent.com/13955303/130456259-994ccfbe-a9a6-4161-8c5e-244fd7cdfc06.mp4

Please ignore the comparison icon missing, my `pi-ui` version is outdated.

2021-08-23 13:49 UTC, tiagoalvesdulce commented on src/components/ModalDiff/CompareVersionSelector.jsx
> +  const versionsOptions = useMemo(() => rangeRight(latest), [latest]);
I think this is causing the issue in my previous comment. When you select a version other than the latest version, the real latest is being cropped out the `versionsOptions`. I suspect that when you are selecting a `version < than the latest` in the version comparison, the `latest` prop is being updated. For example: you have a proposal with 3 versions, I select to compare the version 1 against version 3, all works. Now, if I select to compare version 1 against version 2, latest is being updated to 2. This way 3 is left out of the `versionsOptions` array and I can't select it.

2021-08-23 14:24 UTC, vibros68 commented
> I'm seeing some weird behavior when I play a little bit with the versions selected. In a proposal with 2 versions, if I select to compare the "base version" (empty) against the version 1, I can't go back and compare it against the version 2 if I don't close the modal.

Hi @tiagoalvesdulce . Your problem because the left selector is for base version and the right is for compare version. The compare version is always older than the base version. So if

> I'm seeing some weird behavior when I play a little bit with the versions selected. In a proposal with 2 versions, if I select to compare the "base version" (empty) against the version 1, I can't go back and compare it against the version 2 if I don't close the modal.
> 
Hi @tiagoalvesdulce . Thank you for your review. The bug is appeared because I used wrong way with the `lodash/rangeRight` function. I fixed it and just pushed the code

2021-08-23 14:27 UTC, tiagoalvesdulce approved these changes
LGTM. Good job!

2021-08-23 14:41 UTC, lukebp approved these changes
tACK

2021-08-23 14:46 UTC, merged