fix: Display login option on proposal submission session error.
decred/politeiagui pull request #2541
Opened 2021-08-17 20:41 UTC by victorgcramos

This diff closes #2538, an issue that reported the absence of some login modal when some user submits a proposal with an expired session.

### UI Changes Screenshot

<img width="1341" alt="Screen Shot 2021-08-17 at 5 36 04 PM" src="https://user-images.githubusercontent.com/22639213/129796931-82aad434-e114-4825-a140-1b1051664d28.png">

2021-08-20 23:58 UTC, victorgcramos commented
Improved this PR to comprise all possible expired sessions errors, by improving the `SessionChecker` HOC to display the login modal when some user session expires.

2021-08-29 16:25 UTC, lukebp requested changes
This currently displays the modal as soon as the session expires.  This is not quite what we want.  The modal should be displayed once the session expires AND the user attempts to access a route that requires the user to be logged in (ex. proposal submission, comment submission, etc).

2021-08-30 23:06 UTC, victorgcramos commented
@lukebp handling all requests and displaying the login modal for them will require an extensive refactor because we need to change the way we handle auth errors on forms and other private actions. The Login modal display is an async procedure, so all 403 errors would be displayed in the form error message before the login modal shows up, just like other response errors.

I opted to go for this approach because this way we can avoid those syncing problems mentioned above. After talking to @tiagoalvesdulce, we both agreed that it should be included in the new architecture.

2021-08-31 12:32 UTC, lukebp commented
Ok, that's fine.  We definitely don't want to display the login modal as soon as the session expires though.  We've done this before and it was very annoying for users because they would leave tabs open when reading proposals and would constantly have to log back in.

We have two options:

1. Hardcode the modal behavior to pop up when the session has expired for certain routes.  Probably just the proposal submission and comment submission route for now.

or 

2. Do nothing for now and wait for the new architecture.

Thoughts?
@tiagoalvesdulce @victorgcramos

2021-08-31 12:55 UTC, victorgcramos commented
1 for me is the best.

2021-08-31 13:25 UTC, lukebp commented
Ok, go with option 1 then.

2021-09-01 12:03 UTC, tiagoalvesdulce commented
I'm OK with option 1.

2021-09-07 14:08 UTC, lukebp approved these changes
tACK

2021-09-16 01:17 UTC, lukebp commented
@victorgcramos can you fix the merge conflicts?

This needs final approval from @tiagoalvesdulce.

2021-09-17 17:50 UTC, victorgcramos commented
Let's wait for #2549 first.

2021-09-21 16:04 UTC, amass01 reviewed
Good job, tested and works fine.

I suggest we show the modal also on comment vote. 
Also, added a minor inline comment.

2021-09-21 21:13 UTC, victorgcramos commented on teste2e/cypress/e2e/comments/comments.js
> +    cy.intercept("/api/ticketvote/v1/inventory").as("inventory");
I'd wait until the mocked api structure is done to mock all requests. This is just an alias without any response changes.

2021-09-21 21:37 UTC, amass01 commented on teste2e/cypress/e2e/comments/comments.js
> +    cy.intercept("/api/ticketvote/v1/inventory").as("inventory");
Sweet

2021-09-22 16:13 UTC, amass01 approved these changes
nice work, LGTM!

2021-09-22 16:58 UTC, lukebp commented
Please update your commit message.  Same comment that I said here.

https://github.com/decred/politeiagui/pull/2568#issuecomment-920501890

2021-09-22 17:22 UTC, merged