fix: Autofocus adjustments on 2FA digits input.
decred/politeiagui pull request #2553
Opened 2021-08-26 22:17 UTC by victorgcramos

Closes #2550 

This PR fixes an issue that requested improvements on Two-Factor Authentication digits input regarding its autofocus. Now, the input gets automatically focused after display if the `autoFocus` prop is `true`.

### UI Changes Screenshot
Haven't clicked anywhere after the 2FA modal shows up:
![2550-2fa-focus](https://user-images.githubusercontent.com/22639213/131043176-6794a8c1-43e5-4db8-ab20-118e8924d374.gif)

2021-08-29 15:57 UTC, lukebp requested changes
Found a minor bug.

If you change windows, such as if you pull up your desktop 2fa app to get the 2fa code, the autofocus gets cleared out.

2021-08-29 16:02 UTC, lukebp commented
Are you able to add tests for this?

2021-09-01 12:09 UTC, tiagoalvesdulce commented on src/components/DigitsInput/DigitsInput.jsx
> +  }, [autoFocus]);
Can we get rid of this if we use `const [focused, setFocused] = useState(autoFocus);` ?

2021-09-01 12:10 UTC, tiagoalvesdulce reviewed
Left an inline comment

2021-09-02 14:11 UTC, tiagoalvesdulce commented on src/components/DigitsInput/DigitsInput.jsx
> +  }, [autoFocus]);
Nice! Makes sense. Thanks.

2021-09-07 13:55 UTC, lukebp approved these changes
tACK

2021-09-07 14:34 UTC, tiagoalvesdulce commented on src/components/DigitsInput/DigitsInput.jsx
> +  useEffect(() => {
Just adding to this. It's often a good idea to split up `useEffects` if you can. Even better if you isolate them in custom hooks if they are big and/or reused through the code.

2021-09-16 01:19 UTC, lukebp commented
Needs final approval from @tiagoalvesdulce.

2021-09-20 13:41 UTC, tiagoalvesdulce approved these changes
LGTM. Remember to use https://github.com/decred/dcrd/blob/master/docs/code_contribution_guidelines.md#44-model-git-commit-messages in the PR description in the future. It's easier for the reviewer to merge since the commit description can be reused.

2021-09-20 13:45 UTC, merged