fix: Persist public data after unvetted proposal logout.
decred/politeiagui pull request #2585
Opened 2021-09-14 19:10 UTC by victorgcramos

Closes #2584

This diff fixes the infinite loading issue on unvetted proposal page after author or admin logout, by persisting the public data for unvetted records on the redux store after the logout.

Adds e2e tests for unvetted proposal details logout action.

### UI Changes Screenshot

Before:
![before-2584](https://user-images.githubusercontent.com/22639213/133301825-ffe48c75-6d4a-498e-8539-d6717d83e853.gif)

After:
![unvetted-logout-bug-fix](https://user-images.githubusercontent.com/22639213/133318810-d81d021e-76d2-44a9-86d7-df2e4f0306d3.gif)

2021-09-14 22:04 UTC, thi4go requested changes
Hey mate nice catch! Worked great but I think we need to clear one more thing from the state store on logout. The comments persist for the unvetted proposals which should also go. On a logged out `pictl`:

```
➜  ~ pictl comments 2b69552
400 comments v1 user error code 2, unauthorized: user is not author or admin
```

2021-09-15 18:45 UTC, victorgcramos commented
@thi4go good points! Forgot to remove them! But since #2549 is working on comments stuff, let's wait for it to get merged.

2021-09-21 12:32 UTC, lukebp approved these changes
ACK

Needs final approval from @tiagoalvesdulce.

2021-09-21 20:23 UTC, victorgcramos commented on src/containers/Proposal/Detail/hooks.js
> +  const onReloadProposalDetails = useCallback(
Yeah you're right. Missed that one! Thanks!

2021-09-21 21:08 UTC, victorgcramos commented on src/containers/Proposal/Detail/hooks.js
> +  const onReloadProposalDetails = useCallback(
Actually, the memoized comments list gets re-rendered if `onReloadProposalDetails` is not memoized. Turning this into a regular function would break the optimistic vote updates, for example.

2021-09-22 14:08 UTC, victorgcramos commented
@tiagoalvesdulce ready for final review, mate!

2021-09-22 16:57 UTC, lukebp commented
Please update your commit message.  Same comment that I said here.

https://github.com/decred/politeiagui/pull/2568#issuecomment-920501890

2021-09-22 17:38 UTC, tiagoalvesdulce commented on src/containers/Proposal/Detail/hooks.js
> +  const onReloadProposalDetails = useCallback(
OK then.

2021-09-22 17:40 UTC, merged