[wip] feat: Mark proposals as completed or closed.
decred/politeiagui pull request #2587
Opened 2021-09-16 11:50 UTC by amass01

TBA...

---

Closes #

2021-09-17 22:41 UTC, amass01 commented
Needs a commit message & e2e tests coverage.

2021-09-19 23:11 UTC, amass01 commented
Added e2e test coverage and commit message updated.

2021-09-22 17:33 UTC, lukebp commented
This should be updated once decred/politeia#1515 is in.

An admin should only be able to set the billing status of proposals that have a proposal status of `active`.

2021-09-23 15:26 UTC, amass01 commented on teste2e/cypress/e2e/admin/proposals.js
> +  it.only("Should allow admins to set the billing status of an approved propsoal", () => {
remove that only!

2021-09-28 12:38 UTC, amass01 commented
@lukebp Needs your final OK.

2021-09-28 14:25 UTC, lukebp requested changes
1. The button doesn't go away on the once you set the billing status.  It let's you attempt to set it again and returns an error.

![image](https://user-images.githubusercontent.com/9039877/135106115-bdf70ede-d85f-4ff1-a65f-38eef06da90a.png)

2. The inconsistency between the button text `Set Billing Status` and the modal text `Set billing status` should be corrected.

There currently isn't any way to tell that the billing status of the proposal was updated.  I'm not going to ok this until we can test that functionality.  We need to be able to see a visual indication of the state change, which means #2609 needs to go in before this can go in.

2021-09-28 14:41 UTC, amass01 commented
Closing this PR as we need the set billing status changes with proposal statuses
in order to verify that the proposal status of an proposal updates properly when
setting the billing status.

2021-09-28 14:41 UTC, closed without merging