Update dark mode toggle switch
decred/politeiagui pull request #2588
Opened 2021-09-16 16:52 UTC by vibros68

close #2497 

This pull request update the dark mode toggle to be a new designed toggle. The preview of the toggle here:
![Screenshot from 2021-09-16 23-32-27](https://user-images.githubusercontent.com/84569563/133652426-0bde9a86-9c94-4546-a49a-3878f9145975.png)

It also does some adjustments with nav header style follow [the comment](https://github.com/decred/politeiagui/issues/2497#issuecomment-890911752)

The changes of this pr just can be effective after the [pi-ui/pull/370](https://github.com/decred/pi-ui/pull/370) be merged

2021-09-16 18:45 UTC, lukebp requested changes
I'm seeig a slight delay from when I click the button to when the animation starts.  Is this delay intentional?


https://user-images.githubusercontent.com/9039877/133667819-09bf1cee-b377-47b1-94db-4c94da3cfc06.mp4

2021-09-17 02:19 UTC, vibros68 commented
@lukebp the current delay time for animation effect is 200 mili second. While the change of the variable is immediately. May be I should change the animation effect to 100, so the time seems to fit better

2021-09-17 12:25 UTC, lukebp commented
What about taking out the delay entirely?  It doesn't look like there is one on test-proposals.


https://user-images.githubusercontent.com/9039877/133782184-d116c009-93bc-452d-9a40-f3a07d56c9b1.mp4

2021-09-30 14:55 UTC, lukebp approved these changes
tACK

Needs code approval from @tiagoalvesdulce.

2021-09-30 16:12 UTC, amass01 approved these changes
LGTM!

2021-09-30 17:20 UTC, tiagoalvesdulce approved these changes
LGTM!

2021-09-30 17:20 UTC, tiagoalvesdulce commented on src/components/HeaderNav/HeaderNav.module.css
> +  composes: sharedNavAtribute;
good job using composes!

2021-09-30 17:23 UTC, merged