fix: Record submission error message position
decred/politeiagui pull request #2589
Opened 2021-09-20 14:26 UTC by thi4go

This diff moves the error message position to below the Submit button on the record submission page.

closes #2531 

UI changes:

Desktop:
![image](https://user-images.githubusercontent.com/2729122/134019118-321e1a7d-c060-4945-b1f0-0deea6d107cc.png)

Mobile (iPhone X):
![image](https://user-images.githubusercontent.com/2729122/134019402-1b0a54ad-6de0-4663-bc11-63b7458fd9ce.png)

2021-09-20 15:38 UTC, tiagoalvesdulce requested changes
Left one inline comment

2021-09-20 15:38 UTC, tiagoalvesdulce commented on src/components/ProposalForm/ProposalForm.jsx
> +            id="errorMessage"
can you give a more detailed id? eg: `record-submission-error-message`

2021-09-20 23:50 UTC, victorgcramos approved these changes
ACK!

2021-09-21 12:33 UTC, lukebp approved these changes
ACK

2021-09-21 13:01 UTC, thi4go commented on src/components/ProposalForm/ProposalForm.jsx
> +            id="errorMessage"
addressed mate 👍

2021-09-21 15:21 UTC, thi4go commented
@tiagoalvesdulce addressed the comment mate, ready for review 👍

2021-09-21 16:22 UTC, tiagoalvesdulce approved these changes
LGTM

2021-09-21 16:23 UTC, merged