seo: Add SEO meta tags for CMS and Pi.
decred/politeiagui pull request #2614
Opened 2021-09-27 20:29 UTC by victorgcramos

Closes #2600
Closes #2369

This diff adds SEO meta tags for search engines, Facebook and
Twitter. With these tags, we should be able to provide better results
when searching for "decred politeia", or other keywords, and display a
better preview on Twitter and Facebook posts, including image, app
title and description.

2021-09-28 20:09 UTC, lukebp commented on config/politeia.env
> +REACT_APP_WEBSITE_SUBTITLE="Decred's Governance System"
```suggestion
REACT_APP_WEBSITE_SUBTITLE="Decred's Proposal System"
```

2021-09-28 20:19 UTC, lukebp commented on public/index.html
> +      content="%PUBLIC_URL%/assets/images/%REACT_APP_WEBSITE_BANNER_FILENAME%"
I deployed this on test-proposals to test it. The twitter card image is not coming through.

![image](https://user-images.githubusercontent.com/9039877/135159304-43dfb535-6fef-4e80-9f24-b886bbf37bd1.png)

2021-09-28 21:41 UTC, victorgcramos commented on config/politeia.env
> +REACT_APP_WEBSITE_DESCRIPTION="A platform that supports Decred’s governance. It facilitates the submission, tracking, and discussion of Decred governance proposals by the stakeholder community."
oh, okay! Will change that!

2021-09-28 22:21 UTC, victorgcramos commented on config/politeia.env
> +REACT_APP_WEBSITE_DESCRIPTION="A platform that supports Decred’s governance. It facilitates the submission, tracking, and discussion of Decred governance proposals by the stakeholder community."
Could you give a description with less than 170 chars? The SEO recommendation is to have at most 170.

2021-09-28 22:39 UTC, lukebp commented on config/politeia.env
> +REACT_APP_WEBSITE_DESCRIPTION="A platform that supports Decred’s governance. It facilitates the submission, tracking, and discussion of Decred governance proposals by the stakeholder community."
160 chars

Politeia is Decred's proposal system. It's used to request funding from the Decred treasury. The Decred stakeholders decide how treasury funds are allocated.

2021-09-28 22:42 UTC, lukebp commented on config/politeia.env
> +REACT_APP_WEBSITE_DESCRIPTION="A platform that supports Decred’s governance. It facilitates the submission, tracking, and discussion of Decred governance proposals by the stakeholder community."
Updated it a few times, so make sure you get the most recent edit.

2021-09-29 14:17 UTC, lukebp requested changes
The Politeia image is still not being shown.  Everything else looks good.

![image](https://user-images.githubusercontent.com/9039877/135286899-98d83471-017e-4322-a65d-eec903fd10bd.png)

2021-09-29 22:26 UTC, victorgcramos commented
Here's the preview for Twitter and Facebook:

<img width="509" alt="Screen Shot 2021-09-29 at 7 12 58 PM" src="https://user-images.githubusercontent.com/22639213/135356966-23ef346a-5ed2-4569-801f-6d536422ac95.png"> 
<img width="557" alt="Screen Shot 2021-09-29 at 7 19 41 PM" src="https://user-images.githubusercontent.com/22639213/135356961-883a18a3-b9b1-421b-a843-800e88badbc1.png">

In order to have better images for both, we need to deploy new files to production, since the SEO bots does not render javascript, hence metatag urls must be static.

2021-09-29 22:58 UTC, lukebp approved these changes
tACK

![image](https://user-images.githubusercontent.com/9039877/135359724-3e2b2b78-fb48-4e02-8a91-acc515e0510a.png)

2021-09-29 23:12 UTC, merged

2021-11-11 00:17 UTC, lukebp commented
Before
![image](https://user-images.githubusercontent.com/9039877/141214134-2dfceb1f-b3c5-48a1-84ba-884879f58d17.png)

After
![image](https://user-images.githubusercontent.com/9039877/141214121-65b6a88f-e403-411d-8915-48baf1fbbafa.png)