ux: Add min loading time to list views.
decred/politeiagui pull request #2628
Opened 2021-10-08 12:37 UTC by vibros68

Closes #2586.

This diff adds a minimum timeout of 1.25s when loading the proposal
lists, if the list does not contain any proposals. This creates a
smoother UX since the loading animation is not abruptly cut off.

**Old UX**

https://user-images.githubusercontent.com/9039877/133443369-e6144e7c-3083-4683-8f8e-a69220237804.mp4

**New UX**

https://user-images.githubusercontent.com/9039877/138359346-8a2f66ca-675f-4114-a7d0-6d8840b41651.mp4

2021-10-08 12:45 UTC, vibros68 commented
@lukebp read for review

2021-10-08 14:21 UTC, lukebp requested changes
tACK on firefox.  This UX is much smoother.

https://user-images.githubusercontent.com/9039877/136573298-bf3101e2-19c5-4612-a03a-cb3f2cd4717f.mp4

You need some documentation though.

2021-10-08 14:21 UTC, lukebp commented on src/hooks/api/useProposalsBatch.js
> +          if (isEmpty(tokens)) {
If I was reading this code I wouldn't know why there is an intial wait here.  It's not obvious.  Add some documentation explaining why we do this.

2021-10-08 14:35 UTC, lukebp commented on src/hooks/api/useProposalsBatch.js
> +            // When the tokens is empty and the fetched proposals is empty too.
```suggestion
            // When the tokens are empty and the fetched proposals are empty too,
            // wait 1 second to avoid removing the loading indicator suddenly.
```

2021-10-13 02:56 UTC, vibros68 commented
Thank you @victorgcramos . Your opinion is reasonable. I will change to that way

2021-10-13 09:54 UTC, amass01 reviewed
Can we try this with 500ms ?

2021-10-13 13:32 UTC, lukebp commented
Post videos for 500ms and 1 second so that we can compare the difference.  I think 500ms will probably be too quick.

2021-10-19 13:22 UTC, lukebp requested changes
This doesn't appear to be working anymore with the new implemenation.  Are you seeing the same thing?

https://user-images.githubusercontent.com/9039877/137918149-13027c13-e605-4879-b214-e7f268a19d5f.mp4

2021-10-20 19:48 UTC, victorgcramos requested changes
Hey @vibros68 thanks for the PR 🚀 . Looking really nice. One thing I noticed is that for long lists, the timeout is delayed due to list re-render.

Regarding the timeout, if you take a look at [react-content-loader docs](https://github.com/danilowoz/react-content-loader#options), you'll see `speed={2}` on `src/components/Proposal/ProposalLoader`. So I think the ideal timeout is 2 seconds.

Also, you forgot to define the `PropType` for `minimumInitialLoading`, and I think you should move your default values to `PropType`'s defaults.

Check my inline comment for more info 😁

2021-10-20 19:48 UTC, victorgcramos commented on src/components/LazyList.jsx
> +  }
I think you should wrap this into a `useEffect` to avoid re-renders and improve performance.

```suggestion
  useEffect(() => {
    if (minimumInitialLoading > 0 && initialLoading) {
      setTimeout(() => {
        setInitialLoading(false);
      }, minimumInitialLoading);
    }
  }, [minimumInitialLoading, initialLoading]);
```

2021-10-27 14:25 UTC, merged