fix: Infinite loading on admin approved list
decred/politeiagui pull request #2674
Opened 2021-11-23 18:18 UTC by victorgcramos

Closes #2672.

- Fixes the admin billing changes infinite loading after login with a
previously loaded approved proposals list.

- Adds loading indicator for billing status changes

### Ui Changes
![2672-loading-billing](https://user-images.githubusercontent.com/22639213/143081381-30994b51-b98f-4857-8bda-4e719df1daaf.gif)

2021-11-24 16:46 UTC, lukebp requested changes
1. Don't add a separate loading animation for the button.  Having multiple loading animations all over the place is distracting and bad UX.  The main loading animation should be displayed until all of the data has been retrieved to display the list.

2. This is caught in an infinte loop on refresh, so something is off anyway.


https://user-images.githubusercontent.com/9039877/143280261-4010f80c-0364-4c86-99da-4f856de169c2.mp4

2021-11-24 17:25 UTC, lukebp commented
The infinite loop is actually a loop that fetches all existing approved proposals.  I wasn't able to reproduce it initially becuase I only had a single page of approved proposals in my test env.

2021-11-24 17:43 UTC, lukebp commented
Reproduction steps for button infinite loading on firefox:
1. Load Approved tab without being logged in
2. Log in as an admin
3. Navigate to the Approved tab
4. Refresh the page while on the Approved tab

2021-11-29 20:04 UTC, lukebp requested changes
@victorgcramos I'm not seeing the infinite loading anymore, but the billing status buttons still disappear on refresh.  The infinite loading was caused by the billing statuses not being fetched.  Looks like this is the same root cause.


https://user-images.githubusercontent.com/9039877/143934901-70dc47e7-0fbd-436f-8dcb-08f76ed7b9df.mp4

2021-11-29 22:40 UTC, victorgcramos commented
@lukebp this is how it looks like now. Thanks for the review and the helpful thoughts.

![2672-5-approved](https://user-images.githubusercontent.com/22639213/143953980-b5d082c6-daaf-4579-8575-42b1bd8f964b.gif)

2021-11-29 23:06 UTC, lukebp approved these changes
tACK

Needs code approval from @tiagoalvesdulce.

2021-11-30 11:21 UTC, tiagoalvesdulce approved these changes
LGTM

2021-11-30 11:21 UTC, tiagoalvesdulce commented on src/components/Proposal/ProposalActions.jsx
> +    needsBillingStatus && numbillingstatuschanges < billingstatuschangesmax;
👍

2021-12-01 10:47 UTC, merged