[WIP] e2e: Proposal Create mock structure.
decred/politeiagui pull request #2676
Opened 2021-11-27 04:32 UTC by vibros68

2021-11-28 04:38 UTC, vibros68 commented
@victorgcramos can you review this pr?

2021-11-29 21:53 UTC, victorgcramos requested changes
`records/v1/new` endpoint mock looks good, mate. Thanks! Left some inline comments.

Good to remind that mocking the records/new endpoint does not close the full issue, as It expected the whole proposal/create flow to be mocked so we don't need to be connected to the backend.

2021-11-30 18:54 UTC, victorgcramos requested changes
Looking better now. Tests are working as expected, and thanks for adding an extra test case.

I have some small observations regarding the test cases descriptions: they should start with "should". Left one inline suggestion regarding it, which you should replicate for all test cases you create.

Left some other inline suggestions 😁

2021-11-30 18:54 UTC, victorgcramos commented on teste2e/cypress/support/commands.js
> +  cy.findByTestId("proposal-amount").type(String(proposal.amount / 100)); // get dollars from cents.
Prettier: 80 max char per line.

2021-11-30 18:54 UTC, victorgcramos commented on teste2e/cypress/support/core/api.js
> + * request data with given `files`, `publickey`, `signature` and `author` testParams.
The parameters from this replier doc is different from the replier's parameters.

2021-11-30 18:54 UTC, victorgcramos commented on teste2e/cypress/support/core/api.js
> +import { Record, File, Inventory, Proposal } from "./generate";
`Proposal` is never used and does not exist on generate scope.

2021-11-30 18:54 UTC, victorgcramos commented on teste2e/cypress/e2e/proposal/create.js
> +  it("Paid user can create proposals manually", () => {
```suggestion
  it("should be able to create proposals", () => {
```

2021-12-02 15:20 UTC, victorgcramos requested changes
I'm getting an error on your test run. Please fix it :D

<img width="733" alt="Screen Shot 2021-12-02 at 12 15 34 PM" src="https://user-images.githubusercontent.com/22639213/144449921-bb3673de-ff84-4014-bd46-938914ed4dba.png">

2021-12-02 15:20 UTC, victorgcramos commented on teste2e/cypress/support/commands.js
> +  PROPOSAL_SUMMARY_STATUS_UNVETTED,
Not being used.

2021-12-02 15:20 UTC, victorgcramos commented on teste2e/cypress/support/commands.js
> +  typeDatePicker
Not being used.

2021-12-03 19:56 UTC, victorgcramos requested changes
Looking really good. Left just one minor inline comment, and we should be good to go! Nice job @vibros68

2021-12-03 19:56 UTC, victorgcramos commented on teste2e/cypress/support/core/generate.js
> +      recordSignature,
Noticed some issues here. RecordMetadata has no `recordSignature` field. Actually, it's `signature`. Also, the signature should have a default value.

2021-12-04 12:32 UTC, amass01 commented on teste2e/cypress/e2e/proposal/create.js
> +  it("should be able to create proposals", () => {
```suggestion
  it("should allow paid user to create proposals", () => {
```

2021-12-06 13:55 UTC, victorgcramos approved these changes
tACK!

2021-12-07 12:16 UTC, tiagoalvesdulce approved these changes
LGTM

2021-12-07 12:17 UTC, merged