fix: user menu alignment
decred/politeiagui pull request #2682
Opened 2021-11-30 19:25 UTC by victorgcramos

Closes #2681 

### UI Changes Screenshot

**Before:**
<img width="453" alt="Screen Shot 2021-11-30 at 4 24 22 PM" src="https://user-images.githubusercontent.com/22639213/144114043-265d29c4-8513-4457-9ebb-fd8e9a5c8cd4.png">

**After:**
<img width="447" alt="Screen Shot 2021-11-30 at 4 19 51 PM" src="https://user-images.githubusercontent.com/22639213/144113842-acc128e6-621f-418a-8739-f723426d3627.png">

2021-12-01 13:20 UTC, tiagoalvesdulce requested changes
Although this fixes the menu for mobile, it breaks it for other screen sizes. See:

<img width="610" alt="Screen Shot 2021-12-01 at 10 19 23" src="https://user-images.githubusercontent.com/13955303/144241523-f6d6125e-0122-416e-99ea-b08f8564769e.png">

2021-12-01 13:43 UTC, victorgcramos commented
@tiagoalvesdulce thanks! This is also reproducible on test-proposals. Will push a fix.

2021-12-01 13:51 UTC, victorgcramos commented
![2681-mobile-screen](https://user-images.githubusercontent.com/22639213/144246217-4acbc3ce-1620-4d1b-b01b-e9d4a8c9129b.gif)

2021-12-02 11:19 UTC, tiagoalvesdulce approved these changes

2021-12-02 11:19 UTC, merged