e2e proposal edit mock structure
decred/politeiagui pull request #2692
Opened 2021-12-16 02:37 UTC by vibros68

Closes #2645

This diff implement mock data for edit proposal page. So the teste2e
will not submit to ther server. This  new mock structure introduced by
[#2624](https://github.com/decred/politeiagui/pull/2624).

2021-12-16 15:08 UTC, victorgcramos requested changes
Hey mate, thanks for the PR. Noticed that your first test case hits the `/comments/v1/comments` on the backend. Also, left some inline comments to improve test readability and flow.

Notice that we already use middlewares for making request aliases, so you can use middleware's alias instead of `cy.route()`.

2021-12-18 09:16 UTC, vibros68 commented on teste2e/cypress/support/core/generate.js
> +  const user = author || new User();
`instanceof` work on the normal function. But after pass via cy middleware function, it is nolonger working

2021-12-20 15:47 UTC, victorgcramos approved these changes
LGTM! Just need to fix https://github.com/decred/politeiagui/pull/2692/files#r770595023 and we should be good to go! Good job!

<img width="824" alt="Screen Shot 2021-12-20 at 12 46 05 PM" src="https://user-images.githubusercontent.com/22639213/146794406-39471425-9c74-4020-ba33-2e8025f0c6b5.png">

2021-12-21 01:10 UTC, vibros68 commented
Thank you @victorgcramos

2021-12-29 11:40 UTC, tiagoalvesdulce approved these changes
LGTM! Left a small comment.

2021-12-29 11:40 UTC, tiagoalvesdulce commented on teste2e/cypress/support/core/api.js
> +export function editRecordReply({
I think this comment wasn't addressed.

2021-12-29 13:09 UTC, vibros68 commented on teste2e/cypress/support/core/api.js
> +export function editRecordReply({
It is addressed. If we do not pass the `version` param. The function will generate a randomly greater than 1 value. The code is here: 
`const version = recordVersion || faker.datatype.number(6) + 1;`

2021-12-30 12:26 UTC, tiagoalvesdulce commented on teste2e/cypress/support/core/api.js
> +export function editRecordReply({
oh, my bad

2021-12-30 12:26 UTC, merged