Show proposal vote block heights
decred/politeiagui pull request #2701
Opened 2021-12-29 07:54 UTC by vibros68

Closes #2699 

This diff add  the block start and end heights on the gui for proposal
votes. 
![Screenshot from 2021-12-29 14-50-03](https://user-images.githubusercontent.com/84569563/147639560-f2d259e6-b464-4c9e-87b2-a2d5329e3b88.png)
![Screenshot from 2021-12-29 14-50-21](https://user-images.githubusercontent.com/84569563/147639566-3d3959d8-4a32-4407-a041-328cdeff1b8c.png)

2021-12-29 08:03 UTC, vibros68 commented
Ready for review @lukebp

2021-12-29 11:56 UTC, tiagoalvesdulce approved these changes
Looks good but it won't show on mobile since we aren't showing blocks left too.

2021-12-29 13:05 UTC, vibros68 commented
@tiagoalvesdulce How do you think? Should we display blocks left on mobile?

2022-01-10 18:26 UTC, lukebp requested changes

2022-01-10 18:26 UTC, lukebp commented on src/components/Proposal/Proposal.jsx
> +                      content={`Block heights: ${startblockheight} - ${endblockheight}`}
Let's update this to just:

```suggestion
                      content={`Block ${startblockheight} to ${endblockheight}`}
```

2022-01-10 18:26 UTC, lukebp commented on src/components/Proposal/Proposal.jsx
> +                        {`duration: ${votingBlocks} block${
Let's replace this with the text `Block ${startblockheight} to ${endblockheight}` and remove the tooltip here since it's redundant.

2022-01-10 18:27 UTC, lukebp commented
> Should we display blocks left on mobile?

No, I think it's fine as it.  It's ok if mobile doesn't have the tooltip info.

2022-01-10 20:47 UTC, tiagoalvesdulce commented
Yeah, I think it's fine as well.

2022-01-12 15:55 UTC, lukebp requested changes
Two more UX tweeks.

1.  Let's not capitalize `Block` in `Block xxxx to xxxx`.   `block xxxx to xxxx` is more consistent with the other text.

2. After seeing this, I think it's too cluttered.

![image](https://user-images.githubusercontent.com/9039877/149173760-a9007564-f2ad-47a5-b8ae-a113a61357f5.png)

For proposals that have finished voting, can we display the `block xxxx to xxxx` as a second line in the exiting tooltip that shows the date.  i.e. the tooltip would display:

```
Mon, 10 Jan 2022 18:38:09 GMT
block xxxx to xxxx
```

Lets see how that looks.  I think it will be cleaner.

2022-01-13 19:02 UTC, tiagoalvesdulce commented on src/components/Proposal/Proposal.jsx
> +                  )}*/}
comment

2022-01-14 03:01 UTC, vibros68 commented on src/components/Proposal/Proposal.jsx
> +                  )}*/}
Sorry. My bad

2022-01-14 16:16 UTC, lukebp approved these changes
I do like it better this way.  What do you think @tiagoalvesdulce?

![image](https://user-images.githubusercontent.com/9039877/149548313-a5dafc08-95d6-4bbe-971e-827f6f6b455d.png)
![image](https://user-images.githubusercontent.com/9039877/149548427-ee263e28-f778-41a4-a3bb-7071f7dfa2b9.png)

2022-01-17 18:25 UTC, tiagoalvesdulce commented
I agree.

2022-01-17 18:54 UTC, tiagoalvesdulce approved these changes
Code looks good and works as expected.

2022-01-17 18:54 UTC, merged