e2e: Proposal Details mock structure
decred/politeiagui pull request #2705
Opened 2022-01-10 11:58 UTC by vibros68

Closes #2643

This diff implement mock data for detail proposal page. So the teste2e
process will not submit to the server. The new mock structure introduced
by #2624.

2022-01-10 14:46 UTC, victorgcramos requested changes
Tests are running as expected, and they are not hitting backend endpoints as well. Good job!

<img width="860" alt="Screen Shot 2022-01-10 at 11 46 17 AM" src="https://user-images.githubusercontent.com/22639213/148785067-cde4bc49-292e-4812-847d-70fb8633f1ae.png">

Left some minor inline suggestions for you to improve the code readability.

2022-01-10 14:46 UTC, victorgcramos commented on teste2e/cypress/e2e/proposal/detail.js
> +      cy.wait("@details");
Try this instead:

```javascript
cy.recordsMiddleware("details", {
  error: { errorcode: 13, statusCode: 400 }
});
cy.visit("/record/invalidtoken");
cy.wait("@records.details");
```

2022-01-10 14:46 UTC, victorgcramos commented on teste2e/cypress/e2e/proposal/detail.js
> +        amountByStatus: { ["ineligible"]: 1 }
```suggestion
        amountByStatus: { ineligible: 1 }
```

2022-01-10 14:46 UTC, victorgcramos commented on teste2e/cypress/e2e/proposal/detail.js
> +      cy.piMiddleware("summaries", { amountByStatus: { ["abandoned"]: 1 } });
```suggestion
      cy.piMiddleware("summaries", { amountByStatus: { abandoned: 1 } });
```

2022-01-10 14:46 UTC, victorgcramos commented on teste2e/cypress/e2e/proposal/detail.js
> +        amountByStatus: { ["approved"]: 1 }
```suggestion
        amountByStatus: { approved: 1 }
```

2022-01-10 14:46 UTC, victorgcramos commented on teste2e/cypress/support/core/generate.js
> +        });
It works as expected, but can you improve the readability here? I mean, since this is a string concat., you can use the `${string1}${string2}` pattern. I'd appreciate if you attribute those JSON strings to variables.

2022-01-10 14:46 UTC, victorgcramos commented on teste2e/cypress/utils.js
> +export const PROPOSAL_STATUS_PUBLIC = 2;
is this being used elsewhere?

2022-01-13 19:32 UTC, tiagoalvesdulce approved these changes
LGTM

2022-01-13 19:33 UTC, merged