add e2e: Comments mock structure
decred/politeiagui pull request #2713
Opened 2022-01-17 09:50 UTC by vibros68

Closes #2708

This diff implement mock data for comments on detail proposal page. So
the teste2e process will not submit to the server. The new mock 
structure introduced by #2624.

2022-01-17 14:13 UTC, victorgcramos requested changes
Code looking really good! Clean, readable, simple. Great job!

One thing I noticed is that comments bundle test case is breaking when you run all tests:

![75b60a0a-e112-4a72-ba30-287957c3b0b3](https://user-images.githubusercontent.com/22639213/149785495-af5cb527-5c45-4afd-991a-6bc7d9e62c33.png)


Left some inline comments regarding the old mock api usage and docs.

2022-01-18 14:25 UTC, victorgcramos requested changes
Docs are good. But I think you should move the `general` support structure to the correct place, in order to match the backend design.

2022-01-21 18:35 UTC, vibros68 commented
![Screenshot from 2022-01-22 01-32-00](https://user-images.githubusercontent.com/84569563/150581385-4ba0c559-24ce-4fa1-b8a8-643be6e900cf.png)

I changed commentVotes teste2e to the new structure since it has some problems to be fixed.

2022-01-24 17:22 UTC, victorgcramos requested changes
You shouldn't include commentVotes tests here on this PR, because it's not the correct scope. Also, I noticed that you removed the test cases for comments edits, and you should also include them on the new mock structure.

Left some inline comments.

2022-01-27 15:03 UTC, vibros68 commented on teste2e/cypress/support/core/generate.js
> -
I added and then I do not use it anymore. But I forgot to remove it on that pr. I am sorry. It is my bad.

2022-01-27 15:04 UTC, vibros68 commented on teste2e/cypress/support/core/commands.js
> +            delay,
delay should be the config of the request. While responseParams is the param which is received in the form of the request

2022-01-27 15:06 UTC, victorgcramos commented on teste2e/cypress/support/core/generate.js
> -
no problem! That's fine.

2022-01-27 15:21 UTC, vibros68 commented
![Screenshot from 2022-01-27 16-28-14](https://user-images.githubusercontent.com/84569563/151388437-6027a518-05b5-4ab6-9d96-a8c0086954c0.png)

The last result

2022-01-28 13:12 UTC, victorgcramos approved these changes
LGTM!

2022-02-14 18:36 UTC, tiagoalvesdulce approved these changes
ACK

2022-02-14 18:38 UTC, merged