[WIP] comments: add Comments Plugin
decred/politeiagui pull request #2724
Opened 2022-02-15 19:44 UTC by victorgcramos

Work in Progress ⏳ 

This PR adds the Comments plugin into our new architecture.

> Description to be updated

## UI Changes
<img width="1381" alt="Screen Shot 2022-02-15 at 4 44 34 PM" src="https://user-images.githubusercontent.com/22639213/154137018-b77ec90e-759d-4443-9081-56bfcedeff1a.png">

2022-03-03 20:25 UTC, victorgcramos commented
UI Changes checkpoint:
<img width="896" alt="Screen Shot 2022-03-03 at 5 24 29 PM" src="https://user-images.githubusercontent.com/22639213/156646894-a0e2857c-d85f-4475-855a-2fda4fec90f0.png">

2022-03-11 20:01 UTC, tiagoalvesdulce requested changes
Looks good overall. I left a few inline comments.

2022-03-11 20:35 UTC, victorgcramos commented on plugins-structure/packages/comments/src/comments/votes/votesSlice.js
> +          .sort((a, b) => a.timestamp - b.timestamp) // Order by asc. timestamps
All vote actions are returned by backend. If some user casts two comments votes, the backend will return an array with these two actions, not necessarily ordered by timestamps. Here, I re-order it so we only count the most recent vote.

I'll write down a comment explaining it! Thanks.

2022-03-11 20:36 UTC, victorgcramos commented on plugins-structure/packages/comments/src/ui/Comments/utils.js
> +export function sortByTop(commentsById) {
Much better. Thanks!

2022-03-14 18:59 UTC, tiagoalvesdulce commented on plugins-structure/packages/comments/src/ui/Comments/utils.js
> + */
👍

2022-03-14 19:02 UTC, tiagoalvesdulce commented on plugins-structure/packages/comments/package.json
> +    }
why do we need those presets here?

2022-03-14 19:54 UTC, victorgcramos commented on plugins-structure/packages/comments/package.json
> +    }
The react preset is required in order to make jest recognize the JSX syntax on our tests. If I remove it, I get the following error:

```bash
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.
```

Any thoughts on this? I think adding the preset is enough to fix it.

2022-03-14 21:15 UTC, tiagoalvesdulce commented on plugins-structure/packages/comments/package.json
> +    }
yeah, it's fine to keep it.

2022-03-28 21:17 UTC, tiagoalvesdulce approved these changes
LGTM

2022-03-30 20:55 UTC, merged