feat(common-ui): Add Markdown component.
decred/politeiagui pull request #2741
Opened 2022-03-17 20:55 UTC by victorgcramos

This diff adds the scope for Politeiagui's Markdown component.

Go to `localhost:3007` for a better example.

Includes:
- Markdown Renderer
- Markdown Diff
- Markdown Editor and Commands
- Unit tests for created components and commands

Pros:
- Remove deprecated React-mde package
- Improve markdown diff for lines

2022-03-22 19:30 UTC, tiagoalvesdulce requested changes
Looking pretty good. I think some stuff can be improved:

1. We can make our blockquotes look like github's. Example:

 
<img width="696" alt="Screen Shot 2022-03-22 at 16 07 42" src="https://user-images.githubusercontent.com/13955303/159558405-61b625a6-04b1-48af-a338-95d64262fba4.png">

Will render:

<img width="707" alt="Screen Shot 2022-03-22 at 16 07 47" src="https://user-images.githubusercontent.com/13955303/159558465-4c03489c-307b-4713-8981-10d00bd0e391.png">

But with our markdown editor the same input will render:

<img width="1280" alt="Screen Shot 2022-03-22 at 16 08 41" src="https://user-images.githubusercontent.com/13955303/159558581-21f38203-d351-4e8c-95b8-ac842a63415a.png">

2. We can make our ordered list automatically jump to the next item, like github does:

![numbered_list](https://user-images.githubusercontent.com/13955303/159559192-c8ecbe95-fe81-4563-917d-eda1424a13bb.gif)

3. Any plans to add keyboard shortcuts? Currently on politeia we can make text bold with Cmd+B and italic with Cmd+I. Would be nice to have key bindings for all the itens in the toolbar.
4.  You forgot to add the ordered list to the toolbar.
5. I think we can add the task list to the toolbar as well. I think it would be pretty useful for proposal updates.

2022-03-22 19:43 UTC, tiagoalvesdulce commented on plugins-structure/packages/common-ui/src/components/Markdown/MarkdownEditor/commands.js
> +// import { ReactComponent as NumberedListSVG } from "./assets/numberedList.svg";
comments

2022-03-22 19:43 UTC, tiagoalvesdulce commented on plugins-structure/packages/common-ui/src/components/Markdown/MarkdownEditor/commands.js
> +import BulletListSVG from "./assets/bulletList.svg";
I think we can make those pi-ui icons, right?

2022-03-22 19:48 UTC, victorgcramos commented on plugins-structure/packages/common-ui/src/components/Markdown/MarkdownEditor/commands.js
> +import BulletListSVG from "./assets/bulletList.svg";
That would be great!

2022-03-28 17:57 UTC, tiagoalvesdulce requested changes
Left a comment

2022-03-28 17:57 UTC, tiagoalvesdulce commented on plugins-structure/packages/common-ui/src/components/Markdown/MarkdownEditor/MarkdownEditor.js
> +      // prevent sync issues between textarea updates.
We don't need this setTimeout to achieve the desired behavior here.

First, let's understand why this code actually works. The simple explanation is:

**setState is only async batched when called inside a React event handler.** As `setTimeout` is not a react event handler the `setValue` will be sync here. Crazy, huh? But that's how it works.

A more detailed explanation can be found here: https://github.com/facebook/react/issues/11527#issuecomment-360199710

Now we already know that it's a _hacky_ way to make things work but how do we do it idiomatically? I suggest we use a **useEffect** hook instead. See:

Create a new state:

```
  const [lastCommand, setLastCommand] = useState({});
```

Inside the `handleCommand` function, remove the `setTimeout` hack and call `setLastCommand` with `setValue` and `onChange`. The function will look something like this:

```
const handleCommand =
    (command, { offset = 0, label } = {}) =>
    () => {
      const content = editorRef.current.value;
      const startPos = editorRef.current.selectionStart;
      const endPos = editorRef.current.selectionEnd;
      const newString = executeCommand(command, content, startPos, endPos);
      setLastCommand({ label, offset, startPos, endPos });
      setValue(newString);
      onChange(newString);
    };
```

Now we only have to write a `useEffect` to manipulate the focus like we want and reset the `lastCommand` state:

```
  useEffect(() => {
    if (!isEmpty(lastCommand)) {
      setLastCommand({});
      const { offset, startPos, endPos } = lastCommand;
      editorRef.current.focus();
      editorRef.current.selectionStart = startPos + offset;
      editorRef.current.selectionEnd = endPos + offset;
    }
  }, [lastCommand]);
  ```

2022-04-04 18:08 UTC, tiagoalvesdulce approved these changes
LGTM. Great job!! 👏

2022-04-04 18:08 UTC, merged