[wip] multi: Improve proposals diff and versions
decred/politeiagui pull request #2789
Opened 2022-06-15 19:30 UTC by victorgcramos

Closes #2781 

Work in Progress ⏳ 

TODO:
- [ ] Download Timestamps for different versions
- [ ] Attachments diff

### Preview
Before:
<img width="985" alt="Screen Shot 2022-06-15 at 4 25 03 PM" src="https://user-images.githubusercontent.com/22639213/173908757-1adc80ee-07b0-4ff5-be07-8c6f5c3eaf9a.png">

After
<img width="773" alt="Screen Shot 2022-06-15 at 4 25 10 PM" src="https://user-images.githubusercontent.com/22639213/173908747-35c2f5d9-ede2-4574-b818-931190ee4d4a.png">

2022-06-16 21:24 UTC, victorgcramos commented
### Updated Preview:

<img width="1005" alt="Screen Shot 2022-06-16 at 6 23 53 PM" src="https://user-images.githubusercontent.com/22639213/174168391-80282795-6188-4b81-bafb-b61d35f823fc.png">

2022-06-27 12:53 UTC, tiagoalvesdulce requested changes
In general, I would expect the CSS to be more organized. Using multi-level selectors like `.class > * > * > *` is very hard to read and maintain.

Also, if pi-ui CSS is always taking precedence over politeiagui CSS. We have to fix it there now. Before we pollute our CSS with unnecessary stuff.

2022-06-27 12:53 UTC, tiagoalvesdulce commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +.versionDownloads > * > * > * {
is there any other way to write this selector?

2022-06-27 12:53 UTC, tiagoalvesdulce commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +  min-height: 40vh;
I think the modal can be a bit bigger. Maybe `50vh`?

2022-06-27 12:53 UTC, tiagoalvesdulce commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +  top: -3rem;
Can you elaborate on why we need this negative value?

2022-06-27 12:53 UTC, tiagoalvesdulce commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +    top: -5rem;
Can you elaborate?

2022-06-27 12:53 UTC, tiagoalvesdulce commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +  color: var(--text-secondary-color) !important;
this shouldn't need `!important`. If it does need, it's an issue with pi-ui.

2022-06-27 12:55 UTC, tiagoalvesdulce commented
I have a proposal that two different versions look the same:

https://user-images.githubusercontent.com/13955303/175946513-da1da8e5-8112-498b-84cc-86b8b2c598b8.mp4

2022-06-27 16:36 UTC, victorgcramos commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +.versionDownloads > * > * > * {
That's a pi-ui issue. Will fix that there!

2022-06-27 17:07 UTC, victorgcramos commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +.versionDownloads > * > * > * {
https://github.com/decred/pi-ui/issues/453 reference

2022-06-27 18:25 UTC, victorgcramos commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +.versionDownloads > * > * > * {
Pushed a fix on https://github.com/decred/pi-ui/pull/455

2022-06-27 21:01 UTC, victorgcramos commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +  top: -3rem;
This is required to stick the element on top of the modal.

2022-06-27 21:03 UTC, victorgcramos commented on plugins-structure/apps/politeia/src/components/Proposal/ModalProposalDiff.module.css
> +    top: -5rem;
> This is required to stick the element on top of the modal without extra weird spaces.

same here, but mobile screens have larger spaces

2022-06-28 15:40 UTC, victorgcramos commented
About that unnoticed diff, it's due to markdown formatting behavior. 

After using the same payload as @tiagoalvesdulce, I realized that the difference between the two versions are from line breaks, which are not recognized by the Markdown Renderer. However, the diff is still relevant, so we decided to also add a **raw diff preview** to enhance the changes comparison UX.

2022-06-29 18:58 UTC, tiagoalvesdulce requested changes
Looks good. I like the toggle for markdown and raw diff.

The raw diff is overflowing for medium screen sizes. Also, the `version` dropdown are too small. See: 

<img width="575" alt="Screen Shot 2022-06-29 at 15 57 57" src="https://user-images.githubusercontent.com/13955303/176514504-7f4662d8-fe9f-44e0-a3e7-8c1904c5b6c9.png">

2022-06-29 20:19 UTC, victorgcramos commented
New view for medium screen sizes:

<img width="769" alt="Screen Shot 2022-06-29 at 5 18 14 PM" src="https://user-images.githubusercontent.com/22639213/176537007-7bbb9882-dc77-4868-9931-27307220e34c.png">

2022-06-30 11:49 UTC, merged